/**
 * Themed CSS for the VELLUM shell + components. Illuminated-manuscript palette
 * via CSS variables so skins/host theme can override. Single string loaded via
 * spindle.dom.addStyle.
 */
export const STYLES = [
  ":root{--vle-gold:#cda84e;--vle-gold-soft:rgba(205,168,78,.16);--vle-ink:#e7d6ad;--vle-bg:rgba(20,18,14,.55)}",
  ".vle-root{font-family:'Cormorant Garamond',Georgia,serif;color:var(--vle-ink);padding:10px 12px}",
  ".vle-head{display:flex;align-items:center;gap:7px;font-size:18px;letter-spacing:1px;padding-bottom:8px;border-bottom:1px solid var(--vle-gold-soft)}",
  ".vle-mark{color:var(--vle-gold)}",
  ".vle-ver{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:1px;text-transform:uppercase;opacity:.6;color:var(--vle-gold)}",
  ".vle-stats{margin-left:auto;font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;opacity:.55}",
  // tab bar
  ".vle-tabbar{display:flex;gap:4px;margin:9px 0;flex-wrap:wrap}",
  ".vle-tabbtn{font:600 10px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#cdbfa0;background:rgba(205,168,78,.07);border:1px solid var(--vle-gold-soft);border-radius:7px;padding:6px 11px;cursor:pointer;opacity:.7;transition:opacity .15s,background .15s}",
  ".vle-tabbtn:hover{opacity:.95}",
  ".vle-tabbtn.on{opacity:1;background:rgba(205,168,78,.2);border-color:rgba(205,168,78,.45);color:var(--vle-gold)}",
  ".vle-toolbar{display:flex;flex-wrap:wrap;gap:4px;margin:0 0 10px}",
  ".vle-qol{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#bcae8e;background:rgba(205,168,78,.06);border:1px solid rgba(205,168,78,.18);border-radius:7px;padding:5px 9px;cursor:pointer;transition:background .15s,color .15s}",
  ".vle-qol:hover{background:rgba(205,168,78,.2);color:var(--vle-gold);border-color:rgba(205,168,78,.4)}",
  ".vle-qol[data-qol='clear']:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vle-body{min-height:60px}",
  ".vle-empty{padding:24px 8px;text-align:center;opacity:.65;font-size:14px;line-height:1.6}",
  ".vle-empty.sm{padding:10px;font-size:12px}",
  // section headers + counts
  ".vle-sec-h{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:1px;text-transform:uppercase;opacity:.5;margin:12px 0 6px;display:flex;align-items:center;gap:6px}",
  ".vle-n{font-size:8px;background:var(--vle-gold-soft);color:var(--vle-gold);border-radius:8px;padding:2px 6px}",
  ".vle-scene{font-size:14px;font-style:italic;opacity:.85;padding:4px 2px}",
  ".vle-tension{font:600 9px/1 'JetBrains Mono',monospace;color:#c96a6a;letter-spacing:.5px;margin-left:6px}",
  // cast cards
  ".vle-cards{display:flex;flex-direction:column;gap:5px}",
  ".vle-card{display:flex;align-items:center;gap:9px;padding:7px 9px;border:1px solid var(--vle-gold-soft);border-radius:9px;background:linear-gradient(170deg,rgba(28,25,20,.45),rgba(18,16,12,.35))}",
  ".vle-card.on{border-color:var(--vle-gold);box-shadow:0 0 8px rgba(205,168,78,.18)}",
  ".vle-av{flex:none;width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:rgba(205,168,78,.18);color:var(--vle-gold);font-weight:600;font-size:12px}",
  ".vle-card-main{display:flex;flex-direction:column;gap:1px;min-width:0}",
  ".vle-card-n{font-size:14px}",
  ".vle-star{color:var(--vle-gold);font-size:9px}",
  ".vle-card-meta{font:600 9px/1.2 'JetBrains Mono',monospace;opacity:.6}",
  ".vle-card-app{font-size:11px;opacity:.7;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  // tracks + memory
  ".vle-track{display:flex;justify-content:space-between;gap:8px;font-size:12px;padding:3px 8px;border-left:2px solid var(--vle-gold-soft);margin-bottom:3px}",
  ".vle-track-s{font:600 9px/1.3 'JetBrains Mono',monospace;color:var(--vle-gold);opacity:.8}",
  ".vle-mem{display:flex;gap:7px;font-size:12px;padding:4px 0;line-height:1.45;align-items:baseline}",
  ".vle-mem-tier{flex:none;font:600 7px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.5px;padding:2px 5px;border-radius:5px;opacity:.85}",
  ".vle-mem-tier.t-turn{color:#8c8478;border:1px solid rgba(140,132,120,.4)}",
  ".vle-mem-tier.t-chapter{color:#7ea6b0;border:1px solid rgba(126,166,176,.4)}",
  ".vle-mem-tier.t-arc{color:var(--vle-gold);border:1px solid rgba(205,168,78,.4)}",
  // relations
  ".vle-rel-grid{display:flex;flex-direction:column;gap:7px}",
  ".vle-rel-card{border:1px solid var(--vle-gold-soft);border-radius:9px;padding:8px 10px;background:rgba(22,20,16,.4)}",
  ".vle-rel-top{display:flex;justify-content:space-between;align-items:center;gap:8px}",
  ".vle-rel-pair{font-size:14px}",
  ".vle-rel-sent{font:600 9px/1 'JetBrains Mono',monospace;opacity:.7}",
  ".vle-rel-label{font-size:12px;font-style:italic;opacity:.75;margin:3px 0}",
  ".vle-cats{display:flex;flex-wrap:wrap;gap:4px;margin:5px 0}",
  ".vle-cat{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.5px;padding:2px 6px;border-radius:6px;color:var(--c);border:1px solid color-mix(in srgb,var(--c) 45%,transparent)}",
  ".vle-st{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;padding:2px 6px;border-radius:6px;opacity:.6;border:1px solid var(--vle-gold-soft)}",
  ".vle-bars{display:flex;flex-direction:column;gap:3px;margin-top:4px}",
  ".vle-bar{display:flex;align-items:center;gap:6px}",
  ".vle-bar-l{flex:none;width:30px;font:600 8px/1 'JetBrains Mono',monospace;opacity:.6}",
  ".vle-bar-t{position:relative;flex:1;height:5px;border-radius:3px;background:rgba(255,255,255,.06)}",
  ".vle-bar-mid{position:absolute;left:50%;top:-1px;width:1px;height:7px;background:rgba(255,255,255,.2)}",
  ".vle-bar-f{position:absolute;top:0;height:5px;border-radius:3px}",
  ".vle-bar-f.pos{background:#8fa67e}.vle-bar-f.neg{background:#c96a6a}",
  ".vle-bar-v{flex:none;width:30px;text-align:right;font:600 8px/1 'JetBrains Mono',monospace}",
  ".vle-bar-v.pos{color:#a9c089}.vle-bar-v.neg{color:#e09090}",
  // error boundary
  ".vlm-comp-error{padding:8px;font-size:11px;color:#e09090;border:1px solid rgba(201,106,106,.3);border-radius:8px;background:rgba(201,106,106,.08)}",
  ".vlm-comp-error span{opacity:.7;font-size:10px}",
  // ---- relationship graph ----
  ".vlg-wrap{display:flex;flex-direction:column;gap:8px}",
  ".vlg-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}",
  ".vlg-legend{display:flex;flex-wrap:wrap;gap:4px}",
  ".vlg-leg{display:inline-flex;align-items:center;gap:4px;font:600 8.5px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#cdbfa0;background:rgba(205,168,78,.08);border:1px solid var(--vle-gold-soft);border-radius:20px;padding:3px 9px;cursor:pointer;opacity:.6;transition:opacity .15s,background .15s}",
  ".vlg-leg:hover{opacity:.92}.vlg-leg.on{opacity:1;background:rgba(205,168,78,.2);border-color:rgba(205,168,78,.45)}",
  ".vlg-leg-dot{width:8px;height:8px;border-radius:50%;box-shadow:0 0 5px currentColor}",
  ".vlg-tools{display:flex;gap:4px}",
  ".vlg-tool{min-width:24px;height:24px;display:grid;place-items:center;font:600 13px/1 'JetBrains Mono',monospace;color:var(--vle-gold);background:rgba(205,168,78,.1);border:1px solid rgba(205,168,78,.24);border-radius:6px;cursor:pointer}",
  ".vlg-tool:hover{background:rgba(205,168,78,.22)}.vlg-tool.wide{padding:0 9px;font-size:9px;letter-spacing:.5px;text-transform:uppercase}",
  ".vlg-tool.wide.on{background:rgba(205,168,78,.26);border-color:rgba(205,168,78,.5)}",
  ".vlg-stage{position:relative;border:1px solid var(--vle-gold-soft);border-radius:14px;overflow:hidden;background:radial-gradient(130% 100% at 50% 0%,rgba(205,168,78,.06),transparent 55%),linear-gradient(168deg,rgba(26,22,16,.97),rgba(15,13,10,.99));box-shadow:inset 0 1px 40px rgba(0,0,0,.5),0 2px 18px rgba(0,0,0,.35)}",
  ".vlg-svg{display:block;width:100%;height:auto;min-height:360px;max-height:64vh;cursor:grab;touch-action:none}",
  ".vlg-svg:active{cursor:grabbing}",
  "[data-graph-pan]{transition:transform .09s ease-out}",
  // hulls
  ".vlg-hull-fill{opacity:.08;transition:opacity .3s;pointer-events:none}",
  ".vlg-wrap:hover .vlg-hull-fill{opacity:.12}",
  ".vlg-hull-label{font:600 13px/1 'Cormorant Garamond',Georgia,serif;letter-spacing:2px;text-transform:uppercase;opacity:.5;pointer-events:none}",
  "[data-factions='off'] .vlg-hulls{display:none}",
  // edges
  ".vlg-edge-line{opacity:.6;transition:opacity .2s,stroke-width .2s;filter:drop-shadow(0 0 2px rgba(0,0,0,.55))}",
  ".vlg-edge:hover .vlg-edge-line{opacity:1;stroke-width:5.5}",
  ".vlg-edge-hit{cursor:pointer}",
  // nodes
  ".vlg-node{cursor:grab}.vlg-node.vlg-dragging{cursor:grabbing}",
  ".vlg-node-glow{fill:rgba(205,168,78,0);opacity:0;transition:opacity .25s}",
  ".vlg-node-c{fill:url(#vlgNode);stroke:#8c8478;stroke-width:2;transition:stroke .2s,stroke-width .2s}",
  ".vlg-node-i{fill:#e7d6ad;font:600 12px/1 'Cormorant Garamond',Georgia,serif;letter-spacing:.5px;pointer-events:none;user-select:none}",
  ".vlg-node-l{fill:#cdbfa0;font:600 11px/1 'JetBrains Mono',monospace;opacity:0;transition:opacity .2s;pointer-events:none;paint-order:stroke;stroke:rgba(12,10,8,.92);stroke-width:3.5px}",
  ".vlg-node.is-present .vlg-node-c{fill:#3a2f16;stroke:var(--vle-gold);stroke-width:2.6;filter:url(#vlgGlow)}",
  ".vlg-node.is-present .vlg-node-glow{fill:rgba(205,168,78,.3);opacity:.95}",
  ".vlg-node.is-present .vlg-node-l{opacity:1;fill:#e7d6ad}",
  ".vlg-node.is-user .vlg-node-c{stroke:#e6c07a;stroke-width:3;stroke-dasharray:3 2}",
  ".vlg-node.is-mention .vlg-node-c{opacity:.5;stroke-dasharray:2 3}",
  ".vlg-node:hover .vlg-node-l{opacity:1}.vlg-node:hover .vlg-node-glow{opacity:.85;fill:rgba(205,168,78,.34)}",
  ".vlg-node:hover .vlg-node-c{stroke:var(--vle-gold);stroke-width:3}",
  // focus dimming
  ".vlg-focusing .vlg-edge.vlg-dim .vlg-edge-line{opacity:.08}",
  ".vlg-focusing .vlg-node.vlg-dim{opacity:.2}",
  ".vlg-focusing .vlg-node.vlg-hot .vlg-node-l{opacity:1}",
  ".vlg-node.vlg-hot .vlg-node-c{stroke:var(--vle-gold);stroke-width:3.2}",
  // tooltip
  ".vlg-tip{position:absolute;pointer-events:none;z-index:5;max-width:220px;background:rgba(18,15,11,.97);border:1px solid rgba(205,168,78,.34);border-radius:9px;padding:7px 11px;font:500 11px/1.5 'JetBrains Mono',monospace;color:#d8c9a8;box-shadow:0 8px 26px rgba(0,0,0,.55)}",
  ".vlg-tip b{color:#e7d6ad;font-family:'Cormorant Garamond',Georgia,serif;font-size:14px;letter-spacing:.5px}.vlg-tip span{opacity:.6}",
  ".vlg-hint{font-size:9px;line-height:1.5;opacity:.45;text-align:center;letter-spacing:.3px}",
  // ---- floating window ----
  ".vlf{position:fixed;z-index:9999;opacity:0;transform:translateY(8px) scale(.985);transition:opacity .22s ease,transform .22s cubic-bezier(.2,.8,.2,1);pointer-events:none;font-family:'Cormorant Garamond',Georgia,serif}",
  ".vlf.is-open{opacity:1;transform:none;pointer-events:auto}",
  ".vlf-frame{position:absolute;inset:0;display:flex;flex-direction:column;border-radius:16px;overflow:hidden;color:var(--vle-ink);background:linear-gradient(168deg,rgba(26,22,16,.97),rgba(15,13,10,.985));border:1px solid rgba(205,168,78,.45);box-shadow:0 24px 70px rgba(0,0,0,.6),0 2px 0 rgba(205,168,78,.12),inset 0 0 0 1px rgba(205,168,78,.10),inset 0 1px 50px rgba(205,168,78,.05);backdrop-filter:blur(7px)}",
  ".vlf-frame::before{content:'';position:absolute;inset:5px;border-radius:11px;border:1px solid rgba(205,168,78,.18);pointer-events:none}",
  ".vlf-frame::after{content:'';position:absolute;left:0;right:0;top:0;height:120px;background:radial-gradient(120% 90% at 50% -20%,rgba(205,168,78,.12),transparent 70%);pointer-events:none}",
  ".vlf-bar{position:relative;display:flex;align-items:center;gap:8px;padding:10px 12px 9px;cursor:grab;user-select:none;touch-action:none;border-bottom:1px solid rgba(205,168,78,.2);background:linear-gradient(180deg,rgba(205,168,78,.08),transparent)}",
  ".vlf-bar:active{cursor:grabbing}",
  ".vlf-mark{color:var(--vle-gold);font-size:14px;text-shadow:0 0 8px rgba(205,168,78,.5)}",
  ".vlf-title{font-size:17px;letter-spacing:2px;text-transform:uppercase;color:#e7d6ad}",
  ".vlf-actions{margin-left:auto;display:flex;gap:4px}",
  ".vlf-act{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#cdbfa0;background:rgba(205,168,78,.1);border:1px solid rgba(205,168,78,.26);border-radius:7px;padding:4px 8px;cursor:pointer;transition:background .15s}",
  ".vlf-act:hover{background:rgba(205,168,78,.26);color:var(--vle-gold)}",
  ".vlf-x{width:24px;height:24px;display:grid;place-items:center;border-radius:7px;color:#cdbfa0;background:transparent;border:1px solid transparent;cursor:pointer;font-size:13px}",
  ".vlf-x:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vlf-body{flex:1;overflow-y:auto;padding:12px 14px 16px;scrollbar-width:thin;scrollbar-color:rgba(205,168,78,.4) transparent}",
  ".vlf-body::-webkit-scrollbar{width:8px}.vlf-body::-webkit-scrollbar-thumb{background:rgba(205,168,78,.3);border-radius:4px}",
  ".vlf-grip{position:absolute;right:3px;bottom:3px;width:18px;height:18px;cursor:nwse-resize;touch-action:none;background:linear-gradient(135deg,transparent 45%,rgba(205,168,78,.5) 45%,rgba(205,168,78,.5) 55%,transparent 55%,transparent 70%,rgba(205,168,78,.5) 70%,rgba(205,168,78,.5) 80%,transparent 80%);border-bottom-right-radius:12px}",
  // persistent launcher tab
  ".vlf-launch{position:fixed;right:0;top:46%;z-index:9998;display:flex;align-items:center;gap:6px;padding:9px 10px 9px 12px;border-radius:11px 0 0 11px;cursor:pointer;color:#e7d6ad;font-family:'Cormorant Garamond',Georgia,serif;letter-spacing:1.5px;text-transform:uppercase;font-size:12px;background:linear-gradient(180deg,rgba(34,28,19,.97),rgba(20,17,12,.98));border:1px solid rgba(205,168,78,.45);border-right:none;box-shadow:-4px 4px 18px rgba(0,0,0,.45);transition:transform .18s,box-shadow .18s;writing-mode:vertical-rl}",
  ".vlf-launch:hover{transform:translateX(-3px);box-shadow:-7px 4px 24px rgba(0,0,0,.55)}",
  ".vlf-launch.is-hidden{display:none}",
  ".vlf-launch-mark{color:var(--vle-gold);font-size:14px;writing-mode:horizontal-tb;text-shadow:0 0 8px rgba(205,168,78,.5)}",
  ".vlf-launch-t{opacity:.85}",
  // ---- CRUD controls + pagination ----
  ".vle-sec-top{display:flex;justify-content:flex-end;margin-bottom:8px}",
  ".vle-add{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:var(--vle-gold);background:rgba(205,168,78,.14);border:1px solid rgba(205,168,78,.34);border-radius:7px;padding:5px 11px;cursor:pointer}",
  ".vle-add:hover{background:rgba(205,168,78,.28)}",
  ".vle-add.sm{margin-left:auto;padding:2px 8px;font-size:11px;line-height:1}",
  ".vle-card-ctl,.vle-rel-ctl{display:inline-flex;gap:3px;margin-left:auto}",
  ".vle-mini{width:22px;height:22px;display:grid;place-items:center;border-radius:6px;font-size:11px;color:#cdbfa0;background:rgba(205,168,78,.08);border:1px solid rgba(205,168,78,.2);cursor:pointer}",
  ".vle-mini:hover{background:rgba(205,168,78,.22);color:var(--vle-gold)}",
  ".vle-mini.del:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vle-card{align-items:center}",
  ".vle-rel-sub{margin:2px 0}",
  ".vle-mem{align-items:center;gap:7px}",
  ".vle-pager{display:flex;align-items:center;justify-content:center;gap:10px;margin:8px 0 4px}",
  ".vle-pg{width:26px;height:24px;border-radius:6px;font-size:13px;color:var(--vle-gold);background:rgba(205,168,78,.1);border:1px solid rgba(205,168,78,.24);cursor:pointer}",
  ".vle-pg:hover{background:rgba(205,168,78,.24)}.vle-pg[disabled]{opacity:.3;cursor:default}",
  ".vle-pg-n{font:600 9px/1 'JetBrains Mono',monospace;opacity:.6;min-width:42px;text-align:center}",
  // ---- modal ----
  ".vlfm-overlay{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;background:rgba(8,7,5,.6);backdrop-filter:blur(3px)}",
  ".vlfm{width:min(440px,92vw);max-height:86vh;display:flex;flex-direction:column;border-radius:14px;overflow:hidden;color:var(--vle-ink);background:linear-gradient(168deg,rgba(28,24,17,.99),rgba(16,14,10,1));border:1px solid rgba(205,168,78,.5);box-shadow:0 28px 80px rgba(0,0,0,.7)}",
  ".vlfm-head{display:flex;align-items:center;gap:8px;padding:13px 16px;font-family:'Cormorant Garamond',Georgia,serif;font-size:18px;letter-spacing:1.5px;text-transform:uppercase;color:#e7d6ad;border-bottom:1px solid rgba(205,168,78,.22)}",
  ".vlfm-mark{color:var(--vle-gold)}",
  ".vlfm-body{padding:14px 16px;overflow-y:auto;display:flex;flex-direction:column;gap:11px}",
  ".vlfm-l{display:flex;flex-direction:column;gap:5px;font:600 9px/1.3 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;opacity:.78}",
  ".vlfm-in{font-family:'Cormorant Garamond',Georgia,serif;font-size:15px;letter-spacing:0;text-transform:none;color:var(--vle-ink);background:rgba(12,10,8,.7);border:1px solid rgba(205,168,78,.26);border-radius:8px;padding:8px 10px;outline:none}",
  ".vlfm-in:focus{border-color:var(--vle-gold);box-shadow:0 0 0 2px rgba(205,168,78,.16)}",
  ".vlfm-ta{min-height:84px;resize:vertical;line-height:1.5}",
  ".vlfm-chkrow{display:flex;flex-wrap:wrap;gap:8px 14px;padding:3px 0}",
  ".vlfm-chk{display:inline-flex;align-items:center;gap:5px;font:500 12px/1 'JetBrains Mono',monospace;text-transform:none;letter-spacing:0;cursor:pointer}",
  ".vlfm-chk input{accent-color:var(--vle-gold);cursor:pointer}",
  ".vlfm-foot{display:flex;justify-content:flex-end;gap:8px;padding:11px 16px;border-top:1px solid rgba(205,168,78,.18)}",
  ".vlfm-btn{font:600 11px/1 'JetBrains Mono',monospace;letter-spacing:.5px;border-radius:8px;padding:8px 16px;cursor:pointer;border:1px solid rgba(205,168,78,.3);background:transparent;color:#cdbfa0}",
  ".vlfm-save{background:rgba(205,168,78,.22);color:var(--vle-gold);border-color:rgba(205,168,78,.5)}",
  ".vlfm-save:hover{background:rgba(205,168,78,.36)}.vlfm-cancel:hover{background:rgba(255,255,255,.05)}",
  // ---- filter bar ----
  ".vle-fbar{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 9px}",
  ".vle-fb-btn,.vle-fb-sel{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.4px;color:#cdbfa0;background:rgba(205,168,78,.08);border:1px solid rgba(205,168,78,.22);border-radius:7px;padding:5px 9px;cursor:pointer}",
  ".vle-fb-btn:hover{background:rgba(205,168,78,.2);color:var(--vle-gold)}",
  ".vle-fb-sel{text-transform:none}",
  // ---- journal ----
  ".vle-jr-grid{display:flex;flex-direction:column;gap:7px}",
  ".vle-jr{border:1px solid rgba(205,168,78,.16);border-left:3px solid var(--c,#8c8478);border-radius:0 9px 9px 0;background:rgba(22,20,16,.42);padding:8px 11px}",
  ".vle-jr-top{display:flex;align-items:center;gap:7px}",
  ".vle-jr-glyph{color:var(--c,#cda84e);font-size:14px}",
  ".vle-jr-who{font-family:'Cormorant Garamond',Georgia,serif;font-size:14px;color:#e7d6ad;flex:1}",
  ".vle-jr-ctl{display:inline-flex;gap:3px}",
  ".vle-jr-mem{font-size:12.5px;line-height:1.5;color:#cdc3ad;margin:5px 0 6px;font-style:italic}",
  ".vle-jr-tags{display:flex;flex-wrap:wrap;gap:4px;align-items:center}",
  ".vle-jr-tag{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:5px;border:1px solid rgba(205,168,78,.2);opacity:.85}",
  ".vle-jr-tag.w-defining{border-color:rgba(205,168,78,.6);color:var(--vle-gold)}",
  ".vle-jr-tag.w-significant{border-color:rgba(205,168,78,.4)}",
  ".vle-jr-day{margin-left:auto;font:600 8px/1 'JetBrains Mono',monospace;opacity:.5}",
  // ---- relation change history ----
  ".vle-hist{margin-top:7px;border-top:1px solid rgba(205,168,78,.14);padding-top:5px}",
  ".vle-hist>summary{cursor:pointer;list-style:none;font:600 8.5px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;opacity:.5}",
  ".vle-hist>summary::-webkit-details-marker{display:none}.vle-hist>summary::before{content:'\u25B8 '}",
  ".vle-hist[open]>summary::before{content:'\u25BE '}",
  ".vle-hist-sec{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;opacity:.45;margin:6px 0 3px}",
  ".vle-hist-row{display:flex;gap:7px;align-items:baseline;font-size:11px;padding:1px 0}",
  ".vle-hist-t{flex:none;width:30px;font:600 8px/1 'JetBrains Mono',monospace;opacity:.5}",
  ".vle-hist-ev{font:600 9px/1 'JetBrains Mono',monospace;padding:1px 5px;border-radius:5px}",
  ".vle-hist-ev.add{color:#a9c089;border:1px solid rgba(143,166,126,.4)}",
  ".vle-hist-ev.rm{color:#e09090;border:1px solid rgba(201,106,106,.4);text-decoration:line-through}",
  ".vle-hist-sc{font:600 9px/1.3 'JetBrains Mono',monospace;color:#cdbfa0}",
  ".vle-hist-why{opacity:.55;font-style:italic;font-size:10px}",
  // ---- injection tab ----
  ".vle-inj-hint{font-size:10px;opacity:.55;margin-right:auto}",
  ".vle-inj-list{display:flex;flex-direction:column;gap:6px}",
  ".vle-inj{border:1px solid rgba(205,168,78,.18);border-radius:9px;overflow:hidden;background:rgba(20,18,14,.4)}",
  ".vle-inj-top{display:flex;align-items:center;gap:8px;padding:7px 10px;cursor:pointer}",
  ".vle-inj-top:hover{background:rgba(205,168,78,.06)}",
  ".vle-inj-turn{font:600 9px/1 'JetBrains Mono',monospace;color:var(--vle-gold);flex:none}",
  ".vle-inj-reasons{flex:1;display:flex;flex-wrap:wrap;gap:4px}",
  ".vle-inj-reason{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:5px;background:rgba(205,168,78,.1);color:#cdbfa0}",
  ".vle-inj-chars{font:600 8px/1 'JetBrains Mono',monospace;opacity:.45;flex:none}",
  ".vle-inj-body{display:none;margin:0;padding:9px 11px;border-top:1px solid rgba(205,168,78,.16);font:500 10.5px/1.5 'JetBrains Mono',monospace;color:#bcb29c;white-space:pre-wrap;word-break:break-word;max-height:320px;overflow-y:auto;background:rgba(12,10,8,.5)}",
  ".vle-inj-body.open{display:block}",
  // ---- journal book / shelf ----
  ".vle-shelf{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 9px}",
  ".vle-book{font:600 11px/1 'Cormorant Garamond',Georgia,serif;letter-spacing:.5px;color:#e7d6ad;background:linear-gradient(180deg,rgba(34,28,19,.9),rgba(20,17,12,.9));border:1px solid rgba(205,168,78,.3);border-radius:6px;padding:6px 10px;cursor:pointer;display:inline-flex;align-items:center;gap:6px}",
  ".vle-book:hover{border-color:var(--vle-gold);background:rgba(205,168,78,.16)}",
  ".vle-book-n{font:600 8px/1 'JetBrains Mono',monospace;background:rgba(205,168,78,.2);color:var(--vle-gold);border-radius:7px;padding:2px 6px}",
  ".vle-book-head{display:flex;align-items:center;gap:8px;margin-bottom:9px;padding-bottom:7px;border-bottom:1px solid rgba(205,168,78,.22)}",
  ".vle-book-title{font-family:'Cormorant Garamond',Georgia,serif;font-size:17px;letter-spacing:1px;color:#e7d6ad;flex:1}",
  // ---- floating dashboard ----
  ".vld{display:flex;flex-direction:column;gap:11px}",
  ".vld-sec{display:flex;flex-direction:column;gap:5px}",
  ".vld-h{font:600 8.5px/1 'JetBrains Mono',monospace;letter-spacing:1px;text-transform:uppercase;opacity:.5;display:flex;align-items:center;gap:6px}",
  ".vld-statbar{display:flex;flex-wrap:wrap;gap:6px}",
  ".vld-stat{font:600 10px/1 'JetBrains Mono',monospace;color:#cdbfa0;background:rgba(205,168,78,.08);border:1px solid rgba(205,168,78,.2);border-radius:7px;padding:5px 9px;display:inline-flex;gap:5px}",
  ".vld-stat b{color:var(--vle-gold);font-weight:600;opacity:.8}",
  ".vld-loc{font-family:'Cormorant Garamond',Georgia,serif;font-size:15px;color:#e7d6ad;font-style:italic}",
  ".vld-tension-row{display:flex;align-items:center;gap:10px}",
  ".vld-tension{position:relative;flex:1;height:6px;border-radius:4px;background:rgba(255,255,255,.07)}",
  ".vld-tension-f{position:absolute;left:0;top:0;height:6px;border-radius:4px;transition:width .3s}",
  ".vld-tension-n{flex:none;min-width:34px;text-align:right;font:600 9px/1 'JetBrains Mono',monospace;opacity:.6}",
  ".vld-pc{border:1px solid rgba(205,168,78,.16);border-left:3px solid rgba(205,168,78,.45);border-radius:0 9px 9px 0;background:rgba(22,20,16,.4);padding:7px 10px}",
  ".vld-pc-top{display:flex;align-items:center;gap:7px;flex-wrap:wrap}",
  ".vld-pc-n{font-family:'Cormorant Garamond',Georgia,serif;font-size:15px;color:#e7d6ad}",
  ".vld-mood{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:5px;background:rgba(143,166,126,.18);color:#a9c089}",
  ".vld-cond{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:5px;background:rgba(201,106,106,.16);color:#e09090}",
  ".vld-doing{font-size:12px;opacity:.78;margin-top:3px}",
  ".vld-thought{font-family:'Cormorant Garamond',Georgia,serif;font-style:italic;font-size:13px;color:#c9bd9e;margin-top:4px;opacity:.92}",
  ".vld-rel{display:flex;align-items:center;gap:6px;flex-wrap:wrap;font-size:12px;padding:3px 0}",
  ".vld-rel-p{color:#e7d6ad}.vld-rel-s{margin-left:auto;font:600 8px/1 'JetBrains Mono',monospace;opacity:.6}",
  ".vld-cat{font:600 7.5px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;padding:2px 5px;border-radius:5px;color:var(--c);border:1px solid color-mix(in srgb,var(--c) 45%,transparent)}",
  ".vld-thread{display:flex;justify-content:space-between;gap:8px;font-size:12px;padding:2px 0;border-left:2px solid rgba(205,168,78,.2);padding-left:7px}",
  ".vld-thread-s{font:600 8px/1 'JetBrains Mono',monospace;color:var(--vle-gold);opacity:.75}",
  ".vld-par{border:1px solid rgba(127,168,201,.2);border-radius:8px;background:rgba(20,24,30,.4);padding:6px 9px}",
  ".vld-par-who{font-family:'Cormorant Garamond',Georgia,serif;font-size:13px;color:#9bc0e6}",
  ".vld-par-w{font:600 9px/1 'JetBrains Mono',monospace;opacity:.55}",
  ".vld-par-act{font-size:11.5px;opacity:.8;margin-top:2px}",
  ".vld-rec{font-size:11.5px;line-height:1.5;padding:3px 0;color:#cdc3ad}",
  ".vld-rec-k{font:600 7.5px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.5px;color:var(--vle-gold);background:rgba(205,168,78,.12);border-radius:4px;padding:2px 5px;margin-right:6px}",
  // ---- Vault tab ----
  ".vlv-catbar{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 10px}",
  ".vlv-chip{display:inline-flex;align-items:center;gap:5px;font:600 10px/1 'JetBrains Mono',monospace;letter-spacing:.4px;color:#cdbfa0;background:rgba(205,168,78,.07);border:1px solid var(--vle-gold-soft);border-radius:8px;padding:5px 9px;cursor:pointer;opacity:.78}",
  ".vlv-chip:hover{opacity:1}.vlv-chip.on{opacity:1;border-color:var(--c,rgba(205,168,78,.5));background:color-mix(in srgb,var(--c,#cda84e) 18%,transparent);color:#e7d6ad}",
  ".vlv-chip.add{color:var(--vle-gold);border-style:dashed}",
  ".vlv-glyph{color:var(--c,var(--vle-gold))}",
  ".vlv-cn{font-size:8px;background:rgba(205,168,78,.18);color:var(--vle-gold);border-radius:7px;padding:1px 5px}",
  ".vlv-gear{opacity:.5;margin-left:2px}.vlv-gear:hover{opacity:1;color:var(--vle-gold)}",
  ".vlv-grid{display:flex;flex-direction:column;gap:7px}",
  ".vlv-entry{border:1px solid rgba(205,168,78,.16);border-left:3px solid var(--c,#8c8478);border-radius:0 9px 9px 0;background:rgba(22,20,16,.42);padding:8px 11px}",
  ".vlv-entry.off{opacity:.5}",
  ".vlv-entry-top{display:flex;align-items:center;gap:7px}",
  ".vlv-entry-cat{font:600 8.5px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.5px;color:var(--c,#cdbfa0)}",
  ".vlv-firing{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;color:#a9c089;background:rgba(143,166,126,.18);border-radius:5px;padding:2px 6px}",
  ".vlv-entry-ctl{margin-left:auto;display:inline-flex;gap:3px}",
  ".vlv-keys{font:600 10px/1.3 'JetBrains Mono',monospace;color:var(--vle-gold);margin-top:5px;opacity:.85}",
  ".vlv-content{font-size:12px;line-height:1.5;color:#cdc3ad;margin-top:4px;white-space:pre-wrap;word-break:break-word}",
  ".vlv-badge{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;color:#9bc0e6;margin-top:6px;opacity:.7;display:flex;align-items:center;gap:6px}",
  ".vlv-unlink{font:600 7.5px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.4px;color:#cdbfa0;background:rgba(205,168,78,.08);border:1px solid rgba(205,168,78,.2);border-radius:5px;padding:2px 6px;cursor:pointer}",
  ".vlv-unlink:hover{color:var(--vle-gold);background:rgba(205,168,78,.2)}",
].join('\n');
