/**
 * Themed CSS for the VELLUM shell + components. Illuminated-manuscript palette
 * via CSS variables so skins/host theme can override. Single string loaded via
 * spindle.dom.addStyle.
 */
export const STYLES = [
  // --- theme tokens (overridden at runtime by theme.ts) ---------------------
  // --vg accent (hex) + --vg-rgb its r,g,b ; --vi primary ink, --vi2 muted ink ;
  // --vserif/--vmono fonts ; --vscale chrome size multiplier ; --vsurf-* panel bg.
  ":root{--vg:#cda84e;--vg-rgb:205,168,78;--vi:#e7d6ad;--vi2:#cdbfa0;--vserif:'Cormorant Garamond',Georgia,serif;--vmono:'JetBrains Mono',ui-monospace,monospace;--vscale:1;--vsurf-1:rgba(28,25,20,.5);--vsurf-2:rgba(18,16,12,.4);--vle-gold:var(--vg);--vle-gold-soft:rgba(var(--vg-rgb),.16);--vle-ink:var(--vi);--vle-bg:rgba(20,18,14,.55);--vg2:#9bc0e6;--vg2-rgb:155,192,230;--vai:1;--vdscale:1;--vdensity:1;--vopacity:1;--vblur:8px;--vradius:18px;--vborder:1px;--vink-e:1;--v1:4px;--v2:8px;--v3:12px;--v4:16px;--v5:20px;--v6:24px;--vr1:6px;--vr2:9px;--vr3:13px;--rpill:20px;--v-pos:#8fa67e;--v-pos-i:#a9c089;--v-neg:#c96a6a;--v-neg-i:#e09090;--v-info:#9bc0e6;--v-warn:#b48ed0}",
  // launcher edge + reduced-motion (set on document by theme.ts)
  "html[data-vle-launch='left'] .vlf-launch{right:auto;left:0;border-radius:0 13px 13px 0;border-right:1px solid rgba(var(--vg-rgb),.5);border-left:none;writing-mode:vertical-rl;transform:rotate(180deg)}",
  "html[data-vle-launch='left'] .vlf-launch .vlf-launch-mark,html[data-vle-launch='left'] .vlf-launch .vlf-launch-t{transform:rotate(180deg)}",
  "html[data-vle-launch='hidden'] .vlf-launch{display:none!important}",
  "html[data-vle-motion='off'] *{transition:none!important;animation:none!important}",
  // mono/data text honors its own scale; ink emphasis tints body text
  ".vld-stat,.vld-h,.vld-mood,.vld-cond,.vld-rel-s,.vld-cat,.vld-thread-s,.vld-par-w,.vld-rec-k{font-size:calc(1em * var(--vdscale))}",
  ".vle-root,.vlf-body{opacity:1}",
  ".vle-root{font-family:var(--vserif);color:var(--vle-ink);padding:calc(13px * var(--vscale)) calc(15px * var(--vscale))}",
  ".vle-head{display:flex;align-items:center;gap:9px;font-size:calc(22px * var(--vscale));letter-spacing:1.5px;padding-bottom:calc(11px * var(--vscale));border-bottom:1px solid var(--vle-gold-soft)}",
  ".vle-mark{color:var(--vle-gold);text-shadow:0 0 8px rgba(var(--vg-rgb),.4)}",
  ".vle-ver{font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:1px;text-transform:uppercase;opacity:.6;color:var(--vle-gold)}",
  ".vle-stats{margin-left:auto;font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:.5px;opacity:.6}",
  // tab bar
  ".vle-tabbar{display:flex;gap:5px;margin:calc(11px * var(--vscale)) 0;flex-wrap:wrap}",
  ".vle-tabbtn{font:600 calc(11px * var(--vscale))/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vi2);background:rgba(var(--vg-rgb),.07);border:1px solid var(--vle-gold-soft);border-radius:9px;padding:calc(8px * var(--vscale)) calc(13px * var(--vscale));cursor:pointer;opacity:.72;transition:opacity .15s,background .15s}",
  ".vle-tabbtn:hover{opacity:.95}",
  ".vle-tabbtn.on{opacity:1;background:rgba(var(--vg-rgb),.2);border-color:rgba(var(--vg-rgb),.45);color:var(--vle-gold)}",
  ".vle-toolbar{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 calc(12px * var(--vscale))}",
  ".vle-qol{font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vi2);background:rgba(var(--vg-rgb),.06);border:1px solid rgba(var(--vg-rgb),.18);border-radius:8px;padding:7px 11px;cursor:pointer;transition:background .15s,color .15s}",
  ".vle-qol:hover{background:rgba(var(--vg-rgb),.2);color:var(--vle-gold);border-color:rgba(var(--vg-rgb),.4)}",
  ".vle-qol.on{background:rgba(var(--vg-rgb),.28);color:var(--vle-gold);border-color:var(--vle-gold);box-shadow:inset 0 0 0 1px rgba(var(--vg-rgb),.35)}",
  ".vle-qol.on::before{content:'\\2713 ';opacity:.9}",
  ".vle-qol.busy{color:var(--vle-gold);border-color:rgba(var(--vg-rgb),.5);cursor:progress;opacity:.85}",
  ".vle-qol.busy::before{content:'\\21BB ';display:inline-block;animation:vle-spin 0.9s linear infinite}",
  "@keyframes vle-spin{to{transform:rotate(360deg)}}",
  ".vle-qol[data-qol='clear']:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vle-body{min-height:60px}",
  ".vle-empty{padding:28px 10px;text-align:center;opacity:.65;font-size:calc(15px * var(--vscale));line-height:1.6}",
  ".vle-empty.sm{padding:14px;font-size:calc(13px * var(--vscale))}",
  // section headers + counts
  ".vle-sec-h{font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:1.2px;text-transform:uppercase;color:var(--vg);opacity:.7;margin:calc(15px * var(--vscale)) 0 calc(8px * var(--vscale));display:flex;align-items:center;gap:7px}",
  ".vle-n{font-size:calc(9px * var(--vscale));background:var(--vle-gold-soft);color:var(--vle-gold);border-radius:9px;padding:2px 7px}",
  ".vle-scene{font-size:calc(15px * var(--vscale));font-style:italic;opacity:.85;padding:5px 2px}",
  ".vle-tension{font:600 calc(10px * var(--vscale))/1 var(--vmono);color:var(--v-neg);letter-spacing:.5px;margin-left:6px}",
  // cast cards
  ".vle-cards{display:flex;flex-direction:column;gap:calc(7px * var(--vscale))}",
  ".vle-card{display:flex;align-items:center;gap:11px;padding:calc(10px * var(--vscale)) calc(12px * var(--vscale));border:1px solid var(--vle-gold-soft);border-radius:var(--vr3);background:linear-gradient(170deg,var(--vsurf-1),var(--vsurf-2))}",
  ".vle-card.on{border-color:var(--vle-gold);box-shadow:0 0 10px rgba(var(--vg-rgb),.18)}",
  ".vle-av{flex:none;width:calc(34px * var(--vscale));height:calc(34px * var(--vscale));display:grid;place-items:center;border-radius:50%;background:rgba(var(--vg-rgb),.18);color:var(--vle-gold);font-weight:600;font-size:calc(13px * var(--vscale))}",
  ".vle-card-main{display:flex;flex-direction:column;gap:2px;min-width:0}",
  ".vle-card-n{font-size:calc(16px * var(--vscale))}",
  ".vle-star{color:var(--vle-gold);font-size:calc(10px * var(--vscale))}",
  ".vle-card-meta{font:600 calc(10px * var(--vscale))/1.2 var(--vmono);opacity:.6}",
  ".vle-card-app{font-size:13px;opacity:.72;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  // tracks + memory
  ".vle-track{display:flex;justify-content:space-between;gap:8px;font-size:12px;padding:3px 8px;border-left:2px solid var(--vle-gold-soft);margin-bottom:3px}",
  ".vle-track-s{font:600 9px/1.3 var(--vmono);color:var(--vle-gold);opacity:.8}",
  ".vle-mem{display:flex;gap:7px;font-size:12px;padding:4px 0;line-height:1.45;align-items:baseline}",
  ".vle-mem-tier{flex:none;font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.5px;padding:2px 6px;border-radius:var(--vr1);opacity:.85}",
  ".vle-mem-tier.t-turn{color:#8c8478;border:1px solid rgba(140,132,120,.4)}",
  ".vle-mem-tier.t-chapter{color:var(--v-info);border:1px solid color-mix(in srgb,var(--v-info) 40%,transparent)}",
  ".vle-mem-tier.t-arc{color:var(--vle-gold);border:1px solid rgba(var(--vg-rgb),.4)}",
  // knowledge epistemic chips (reliability + truth)
  ".vle-krel{display:inline-block;font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:var(--vr1);margin-right:5px;vertical-align:middle;opacity:.9}",
  ".vle-krel-believes{color:#c8a24e;border:1px solid rgba(200,162,78,.4)}",
  ".vle-krel-suspects{color:var(--v-warn);border:1px solid color-mix(in srgb,var(--v-warn) 40%,transparent)}",
  ".vle-krel-wrong{color:var(--v-neg-i);border:1px solid color-mix(in srgb,var(--v-neg) 50%,transparent);background:color-mix(in srgb,var(--v-neg) 8%,transparent)}",
  ".vle-krel-unaware{color:#8c8478;border:1px solid rgba(140,132,120,.4)}",
  ".vle-kfalse{display:inline-block;font:600 9px/1 var(--vmono);color:var(--v-neg-i);margin-right:5px;opacity:.85}",
  // relations
  ".vle-rel-grid{display:flex;flex-direction:column;gap:7px}",
  ".vle-rel-card{border:1px solid var(--vle-gold-soft);border-radius:9px;padding:8px 10px;background:rgba(22,20,16,.4)}",
  ".vle-rel-top{display:flex;justify-content:space-between;align-items:center;gap:8px}",
  ".vle-rel-pair{font-size:14px}",
  ".vle-rel-sent{font:600 9px/1 var(--vmono);opacity:.7}",
  ".vle-rel-label{font-size:12px;font-style:italic;opacity:.75;margin:3px 0}",
  ".vle-cats{display:flex;flex-wrap:wrap;gap:4px;margin:5px 0}",
  ".vle-cat{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.5px;padding:2px 6px;border-radius:var(--vr1);color:var(--c);border:1px solid color-mix(in srgb,var(--c) 45%,transparent)}",
  ".vle-st{font:600 9px/1 var(--vmono);text-transform:uppercase;padding:2px 6px;border-radius:var(--vr1);opacity:.6;border:1px solid var(--vle-gold-soft)}",
  ".vle-bars{display:flex;flex-direction:column;gap:3px;margin-top:4px}",
  ".vle-bar{display:flex;align-items:center;gap:6px}",
  ".vle-bar-l{flex:none;width:30px;font:600 9px/1 var(--vmono);opacity:.6}",
  ".vle-bar-t{position:relative;flex:1;height:5px;border-radius:3px;background:rgba(255,255,255,.06)}",
  ".vle-bar-mid{position:absolute;left:50%;top:-1px;width:1px;height:7px;background:rgba(255,255,255,.2)}",
  ".vle-bar-f{position:absolute;top:0;height:5px;border-radius:3px}",
  ".vle-bar-f.pos{background:var(--v-pos)}.vle-bar-f.neg{background:var(--v-neg)}",
  ".vle-bar-v{flex:none;width:30px;text-align:right;font:600 9px/1 var(--vmono)}",
  ".vle-bar-v.pos{color:var(--v-pos-i)}.vle-bar-v.neg{color:var(--v-neg-i)}",
  // error boundary
  ".vlm-comp-error{padding:8px;font-size:11px;color:#e09090;border:1px solid rgba(201,106,106,.3);border-radius:8px;background:rgba(201,106,106,.08)}",
  ".vlm-comp-error span{opacity:.7;font-size:10px}",
  // ---- relationship graph ----
  ".vlg-wrap{display:flex;flex-direction:column;gap:8px}",
  ".vlg-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}",
  ".vlg-legend{display:flex;flex-wrap:wrap;gap:4px}",
  ".vlg-leg{display:inline-flex;align-items:center;gap:4px;font:600 9px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid var(--vle-gold-soft);border-radius:20px;padding:3px 9px;cursor:pointer;opacity:.6;transition:opacity .15s,background .15s}",
  ".vlg-leg:hover{opacity:.92}.vlg-leg.on{opacity:1;background:rgba(var(--vg-rgb),.2);border-color:rgba(var(--vg-rgb),.45)}",
  ".vlg-leg-dot{width:8px;height:8px;border-radius:50%;box-shadow:0 0 5px currentColor}",
  ".vlg-tools{display:flex;gap:4px}",
  ".vlg-tool{min-width:24px;height:24px;display:grid;place-items:center;font:600 13px/1 var(--vmono);color:var(--vle-gold);background:rgba(var(--vg-rgb),.1);border:1px solid rgba(var(--vg-rgb),.24);border-radius:6px;cursor:pointer}",
  ".vlg-tool:hover{background:rgba(var(--vg-rgb),.22)}.vlg-tool.wide{padding:0 9px;font-size:9px;letter-spacing:.5px;text-transform:uppercase}",
  ".vlg-tool.wide.on{background:rgba(var(--vg-rgb),.26);border-color:rgba(var(--vg-rgb),.5)}",
  ".vlg-stage{position:relative;border:1px solid var(--vle-gold-soft);border-radius:14px;overflow:hidden;background:radial-gradient(130% 100% at 50% 0%,rgba(var(--vg-rgb),.06),transparent 55%),linear-gradient(168deg,rgba(26,22,16,.97),rgba(15,13,10,.99));box-shadow:inset 0 1px 40px rgba(0,0,0,.5),0 2px 18px rgba(0,0,0,.35)}",
  ".vlg-svg{display:block;width:100%;height:auto;min-height:360px;max-height:64vh;cursor:grab;touch-action:none}",
  ".vlg-svg:active{cursor:grabbing}",
  "[data-graph-pan]{transition:transform .09s ease-out}",
  // hulls
  ".vlg-hull-fill{opacity:.08;transition:opacity .3s;pointer-events:none}",
  ".vlg-wrap:hover .vlg-hull-fill{opacity:.12}",
  ".vlg-hull-label{font:600 13px/1 var(--vserif);letter-spacing:2px;text-transform:uppercase;opacity:.5;pointer-events:none}",
  "[data-factions='off'] .vlg-hulls{display:none}",
  // edges
  ".vlg-edge-line{opacity:.6;transition:opacity .2s,stroke-width .2s;filter:drop-shadow(0 0 2px rgba(0,0,0,.55))}",
  ".vlg-edge:hover .vlg-edge-line{opacity:1;stroke-width:5.5}",
  ".vlg-edge-hit{cursor:pointer}",
  // nodes
  ".vlg-node{cursor:grab}.vlg-node.vlg-dragging{cursor:grabbing}",
  ".vlg-node-glow{fill:rgba(var(--vg-rgb),0);opacity:0;transition:opacity .25s}",
  ".vlg-node-c{fill:url(#vlgNode);stroke:#8c8478;stroke-width:2;transition:stroke .2s,stroke-width .2s}",
  ".vlg-node-i{fill:var(--vi);font:600 12px/1 var(--vserif);letter-spacing:.5px;pointer-events:none;user-select:none}",
  ".vlg-node-l{fill:var(--vi2);font:600 11px/1 var(--vmono);opacity:0;transition:opacity .2s;pointer-events:none;paint-order:stroke;stroke:rgba(12,10,8,.92);stroke-width:3.5px}",
  ".vlg-node.is-present .vlg-node-c{fill:#3a2f16;stroke:var(--vle-gold);stroke-width:2.6;filter:url(#vlgGlow)}",
  ".vlg-node.is-present .vlg-node-glow{fill:rgba(var(--vg-rgb),.3);opacity:.95}",
  ".vlg-node.is-present .vlg-node-l{opacity:1;fill:var(--vi)}",
  ".vlg-node.is-user .vlg-node-c{stroke:#e6c07a;stroke-width:3;stroke-dasharray:3 2}",
  ".vlg-node.is-mention .vlg-node-c{opacity:.5;stroke-dasharray:2 3}",
  ".vlg-node:hover .vlg-node-l{opacity:1}.vlg-node:hover .vlg-node-glow{opacity:.85;fill:rgba(var(--vg-rgb),.34)}",
  ".vlg-node:hover .vlg-node-c{stroke:var(--vle-gold);stroke-width:3}",
  // focus dimming
  ".vlg-focusing .vlg-edge.vlg-dim .vlg-edge-line{opacity:.08}",
  ".vlg-focusing .vlg-node.vlg-dim{opacity:.2}",
  ".vlg-focusing .vlg-node.vlg-hot .vlg-node-l{opacity:1}",
  ".vlg-node.vlg-hot .vlg-node-c{stroke:var(--vle-gold);stroke-width:3.2}",
  // tooltip
  ".vlg-tip{position:absolute;pointer-events:none;z-index:5;max-width:220px;background:rgba(18,15,11,.97);border:1px solid rgba(var(--vg-rgb),.34);border-radius:9px;padding:7px 11px;font:500 11px/1.5 var(--vmono);color:#d8c9a8;box-shadow:0 8px 26px rgba(0,0,0,.55)}",
  ".vlg-tip b{color:var(--vi);font-family:var(--vserif);font-size:14px;letter-spacing:.5px}.vlg-tip span{opacity:.6}",
  ".vlg-hint{font-size:9px;line-height:1.5;opacity:.45;text-align:center;letter-spacing:.3px}",
  // ---- floating window ----
  ".vlf{position:fixed;z-index:9999;opacity:0;transform:translateY(8px) scale(.985);transition:opacity .22s ease,transform .22s cubic-bezier(.2,.8,.2,1);pointer-events:none;font-family:var(--vserif)}",
  ".vlf.is-open{opacity:1;transform:none;pointer-events:auto}",
  ".vlf-frame{position:absolute;inset:0;display:flex;flex-direction:column;border-radius:var(--vradius,18px);overflow:hidden;color:var(--vle-ink);background:transparent;border:var(--vborder,1px) solid rgba(var(--vg-rgb),calc(.5 * var(--vai,1)));box-shadow:0 28px 80px rgba(0,0,0,.62),0 2px 0 rgba(var(--vg-rgb),.14),inset 0 0 0 1px rgba(var(--vg-rgb),calc(.1 * var(--vai,1))),inset 0 1px 60px rgba(var(--vg-rgb),.05);backdrop-filter:blur(var(--vblur,8px))}",
  ".vlf-tex{position:absolute;inset:0;z-index:0;background:var(--vglass,linear-gradient(168deg,rgba(26,22,16,.97),rgba(15,13,10,.985)));opacity:var(--vopacity,1);pointer-events:none}",
  ".vlf-scrim{position:absolute;inset:0;z-index:0;background-image:var(--vtexture,none);background-size:140px,16px 16px,16px 16px;opacity:.5;mix-blend-mode:overlay;pointer-events:none}",
  ".vlf-bar,.vlf-body,.vlf-grip{position:relative;z-index:1}",
  "[data-vle-chrome='illuminated'] .vlf-frame::before{content:'';position:absolute;z-index:1;inset:6px;border-radius:calc(var(--vradius,18px) - 5px);border:1px solid rgba(var(--vg-rgb),calc(.2 * var(--vai,1)));pointer-events:none}",
  "[data-vle-chrome='illuminated'] .vlf-frame::after{content:'';position:absolute;left:0;right:0;top:0;height:150px;background:radial-gradient(130% 90% at 50% -25%,rgba(var(--vg-rgb),.14),transparent 70%);pointer-events:none}",
  ".vlf-bar{position:relative;display:flex;align-items:center;gap:10px;padding:calc(13px * var(--vscale)) calc(16px * var(--vscale)) calc(11px * var(--vscale));cursor:grab;user-select:none;touch-action:none;border-bottom:1px solid rgba(var(--vg-rgb),.22);background:linear-gradient(180deg,rgba(var(--vg-rgb),.09),transparent)}",
  ".vlf-bar:active{cursor:grabbing}",
  ".vlf-mark{color:var(--vle-gold);font-size:calc(16px * var(--vscale));text-shadow:0 0 10px rgba(var(--vg-rgb),.55)}",
  ".vlf-title{font-family:var(--vserif);font-size:calc(20px * var(--vscale));letter-spacing:3px;text-transform:uppercase;color:var(--vi)}",
  ".vlf-actions{margin-left:auto;display:flex;gap:5px}",
  ".vlf-act{font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vi2);background:rgba(var(--vg-rgb),.1);border:1px solid rgba(var(--vg-rgb),.26);border-radius:8px;padding:6px 10px;cursor:pointer;transition:background .15s}",
  ".vlf-act:hover{background:rgba(var(--vg-rgb),.26);color:var(--vle-gold)}",
  ".vlf-x{width:calc(26px * var(--vscale));height:calc(26px * var(--vscale));display:grid;place-items:center;border-radius:8px;color:var(--vi2);background:transparent;border:1px solid transparent;cursor:pointer;font-size:calc(14px * var(--vscale))}",
  ".vlf-x:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vlf-body{flex:1;overflow-y:auto;padding:calc(16px * var(--vscale)) calc(18px * var(--vscale)) calc(20px * var(--vscale));scrollbar-width:thin;scrollbar-color:rgba(var(--vg-rgb),.4) transparent}",
  ".vlf-body::-webkit-scrollbar{width:9px}.vlf-body::-webkit-scrollbar-thumb{background:rgba(var(--vg-rgb),.3);border-radius:5px;border:2px solid transparent;background-clip:padding-box}",
  ".vlf-grip{position:absolute;right:3px;bottom:3px;width:18px;height:18px;cursor:nwse-resize;touch-action:none;background:linear-gradient(135deg,transparent 45%,rgba(var(--vg-rgb),.5) 45%,rgba(var(--vg-rgb),.5) 55%,transparent 55%,transparent 70%,rgba(var(--vg-rgb),.5) 70%,rgba(var(--vg-rgb),.5) 80%,transparent 80%);border-bottom-right-radius:12px}",
  // persistent launcher tab
  ".vlf-launch{position:fixed;right:0;top:46%;z-index:9998;display:flex;align-items:center;gap:6px;padding:11px 11px 11px 13px;border-radius:13px 0 0 13px;cursor:pointer;color:var(--vi);font-family:var(--vserif);letter-spacing:1.5px;text-transform:uppercase;font-size:13px;background:var(--vglass,linear-gradient(180deg,rgba(34,28,19,.97),rgba(20,17,12,.98)));border:1px solid rgba(var(--vg-rgb),.5);border-right:none;box-shadow:-5px 4px 22px rgba(0,0,0,.5);transition:transform .18s,box-shadow .18s;writing-mode:vertical-rl}",
  ".vlf-launch:hover{transform:translateX(-3px);box-shadow:-7px 4px 24px rgba(0,0,0,.55)}",
  ".vlf-launch.is-hidden{display:none}",
  ".vlf-launch-mark{color:var(--vle-gold);font-size:14px;writing-mode:horizontal-tb;text-shadow:0 0 8px rgba(var(--vg-rgb),.5)}",
  ".vlf-launch-t{opacity:.85}",
  // ---- window chrome modes (orthogonal to skin; default = illuminated above) ----
  // MODERN — flat, quiet, sans title, no manuscript ornament
  "[data-vle-chrome='modern'] .vlf-frame{border-color:rgba(var(--vg-rgb),calc(.28 * var(--vai,1)));box-shadow:0 18px 50px rgba(0,0,0,.5),inset 0 0 0 1px rgba(var(--vg-rgb),.05)}",
  "[data-vle-chrome='modern'] .vlf-bar{background:rgba(var(--vg-rgb),.05);border-bottom-color:rgba(var(--vg-rgb),.14)}",
  "[data-vle-chrome='modern'] .vlf-title{font-family:var(--vserif);font-size:calc(16px * var(--vscale));letter-spacing:.5px;text-transform:none}",
  "[data-vle-chrome='modern'] .vlf-mark{text-shadow:none}",
  "[data-vle-chrome='modern'] .vlf-grip{background:none;border:none;right:5px;bottom:5px;width:12px;height:12px;border-right:2px solid rgba(var(--vg-rgb),.4);border-bottom:2px solid rgba(var(--vg-rgb),.4);border-bottom-right-radius:4px}",
  // FUTURISTIC — sharp, accent edge-glow, mono HUD title, corner ticks
  "[data-vle-chrome='futuristic'] .vlf-frame{border-color:rgba(var(--vg-rgb),calc(.7 * var(--vai,1)));box-shadow:0 0 0 1px rgba(var(--vg-rgb),.25),0 0 22px rgba(var(--vg-rgb),.22),0 18px 50px rgba(0,0,0,.6)}",
  "[data-vle-chrome='futuristic'] .vlf-bar{background:linear-gradient(180deg,rgba(var(--vg-rgb),.16),transparent);border-bottom-color:rgba(var(--vg-rgb),.45)}",
  "[data-vle-chrome='futuristic'] .vlf-title{font-family:var(--vmono);font-size:calc(14px * var(--vscale));font-weight:600;letter-spacing:2px;text-transform:uppercase}",
  "[data-vle-chrome='futuristic'] .vlf-frame::before{content:'';position:absolute;z-index:1;inset:4px;border-radius:2px;border:1px solid rgba(var(--vg-rgb),.18);pointer-events:none}",
  "[data-vle-chrome='futuristic'] .vlf-frame::after{content:'';position:absolute;z-index:1;inset:0;pointer-events:none;background:linear-gradient(90deg,var(--vg) 0 14px,transparent 14px) 0 0/100% 2px no-repeat,linear-gradient(90deg,var(--vg) 0 14px,transparent 14px) 100% 100%/100% 2px no-repeat;opacity:.55}",
  "[data-vle-chrome='futuristic'] .vlf-grip{background:none;border:none;right:4px;bottom:4px;width:12px;height:12px;border-right:2px solid var(--vg);border-bottom:2px solid var(--vg);opacity:.7;border-radius:0}",
  "[data-vle-chrome='futuristic'] .vlf-launch{border-radius:0;border-width:1px 0 1px 1px}",
  // ---- CRUD controls + pagination ----
  ".vle-sec-top{display:flex;justify-content:flex-end;margin-bottom:8px}",
  ".vle-add{font:600 9px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vle-gold);background:rgba(var(--vg-rgb),.14);border:1px solid rgba(var(--vg-rgb),.34);border-radius:7px;padding:5px 11px;cursor:pointer}",
  ".vle-add:hover{background:rgba(var(--vg-rgb),.28)}",
  ".vle-add.sm{margin-left:auto;padding:2px 8px;font-size:11px;line-height:1}",
  ".vle-card-ctl,.vle-rel-ctl{display:inline-flex;gap:3px;margin-left:auto}",
  // controls fade in on hover/keyboard-focus; only hidden where hover exists, so
  // touch devices (hover:none) keep them tappable. Kept in DOM (not display:none).
  "@media (hover:hover){.vle-card .vle-card-ctl{opacity:0;transition:opacity .15s}.vle-card:hover .vle-card-ctl,.vle-card:focus-within .vle-card-ctl{opacity:1}}",
  "html[data-vle-motion='off'] .vle-card .vle-card-ctl{opacity:1}",
  ".vle-mini{width:22px;height:22px;display:grid;place-items:center;border-radius:6px;font-size:11px;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid rgba(var(--vg-rgb),.2);cursor:pointer}",
  ".vle-mini:hover{background:rgba(var(--vg-rgb),.22);color:var(--vle-gold)}",
  ".vle-mini.del:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vle-card{align-items:center}",
  ".vle-rel-sub{margin:2px 0}",
  ".vle-mem{align-items:center;gap:7px}",
  ".vle-pager{display:flex;align-items:center;justify-content:center;gap:10px;margin:8px 0 4px}",
  ".vle-pg{width:26px;height:24px;border-radius:6px;font-size:13px;color:var(--vle-gold);background:rgba(var(--vg-rgb),.1);border:1px solid rgba(var(--vg-rgb),.24);cursor:pointer}",
  ".vle-pg:hover{background:rgba(var(--vg-rgb),.24)}.vle-pg[disabled]{opacity:.3;cursor:default}",
  ".vle-pg-n{font:600 9px/1 var(--vmono);opacity:.6;min-width:42px;text-align:center}",
  // ---- modal ----
  ".vlfm-overlay{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;background:rgba(8,7,5,.6);backdrop-filter:blur(3px)}",
  ".vlfm{width:min(440px,92vw);max-height:86vh;display:flex;flex-direction:column;border-radius:14px;overflow:hidden;color:var(--vle-ink);background:linear-gradient(168deg,rgba(28,24,17,.99),rgba(16,14,10,1));border:1px solid rgba(var(--vg-rgb),.5);box-shadow:0 28px 80px rgba(0,0,0,.7)}",
  ".vlfm-head{display:flex;align-items:center;gap:8px;padding:13px 16px;font-family:var(--vserif);font-size:18px;letter-spacing:1.5px;text-transform:uppercase;color:var(--vi);border-bottom:1px solid rgba(var(--vg-rgb),.22)}",
  ".vlfm-mark{color:var(--vle-gold)}",
  ".vlfm-body{padding:14px 16px;overflow-y:auto;display:flex;flex-direction:column;gap:11px}",
  ".vlfm-l{display:flex;flex-direction:column;gap:5px;font:600 9px/1.3 var(--vmono);letter-spacing:.5px;text-transform:uppercase;opacity:.78}",
  ".vlfm-in{font-family:var(--vserif);font-size:15px;letter-spacing:0;text-transform:none;color:var(--vle-ink);background:rgba(12,10,8,.7);border:1px solid rgba(var(--vg-rgb),.26);border-radius:8px;padding:8px 10px;outline:none}",
  ".vlfm-in:focus{border-color:var(--vle-gold);box-shadow:0 0 0 2px rgba(var(--vg-rgb),.16)}",
  ".vlfm-ta{min-height:84px;resize:vertical;line-height:1.5}",
  // large editor (vault entries): wide dialog + tall content area, with a body that grows
  ".vlfm-large{width:min(860px,94vw);max-height:90vh}",
  ".vlfm-large .vlfm-body{flex:1 1 auto}",
  ".vlfm-l-grow{flex:1 1 auto;min-height:0}",
  ".vlfm-ta-big{min-height:min(58vh,520px);height:min(58vh,520px);resize:vertical;line-height:1.6;font-size:15px}",
  ".vlfm-chkrow{display:flex;flex-wrap:wrap;gap:8px 14px;padding:3px 0}",
  ".vlfm-chk{display:inline-flex;align-items:center;gap:5px;font:500 12px/1 var(--vmono);text-transform:none;letter-spacing:0;cursor:pointer}",
  ".vlfm-chk input{accent-color:var(--vle-gold);cursor:pointer}",
  ".vlfm-foot{display:flex;justify-content:flex-end;gap:8px;padding:11px 16px;border-top:1px solid rgba(var(--vg-rgb),.18)}",
  ".vlfm-btn{font:600 11px/1 var(--vmono);letter-spacing:.5px;border-radius:8px;padding:8px 16px;cursor:pointer;border:1px solid rgba(var(--vg-rgb),.3);background:transparent;color:var(--vi2)}",
  ".vlfm-save{background:rgba(var(--vg-rgb),.22);color:var(--vle-gold);border-color:rgba(var(--vg-rgb),.5)}",
  ".vlfm-save:hover{background:rgba(var(--vg-rgb),.36)}.vlfm-cancel:hover{background:rgba(255,255,255,.05)}",
  // ---- filter bar ----
  ".vle-fbar{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 9px}",
  ".vle-fb-btn,.vle-fb-sel{font:600 9px/1 var(--vmono);letter-spacing:.4px;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid rgba(var(--vg-rgb),.22);border-radius:7px;padding:5px 9px;cursor:pointer}",
  ".vle-fb-btn:hover{background:rgba(var(--vg-rgb),.2);color:var(--vle-gold)}",
  ".vle-fb-btn.on{background:rgba(var(--vg-rgb),.2);color:var(--vle-gold);border-color:rgba(var(--vg-rgb),.45)}",
  ".vle-fb-sel{text-transform:none}",
  // ---- journal ----
  ".vle-jr-grid{display:flex;flex-direction:column;gap:7px}",
  ".vle-jr{border:1px solid rgba(var(--vg-rgb),.16);border-left:3px solid var(--c,#8c8478);border-radius:0 var(--vr2) var(--vr2) 0;background:rgba(22,20,16,.42);padding:8px 11px}",
  ".vle-jr-top{display:flex;align-items:center;gap:7px}",
  ".vle-jr-glyph{color:var(--c,var(--vg));font-size:14px}",
  ".vle-jr-who{font-family:var(--vserif);font-size:14px;color:var(--vi);flex:1}",
  ".vle-jr-ctl{display:inline-flex;gap:3px}",
  ".vle-jr-mem{font-size:12.5px;line-height:1.5;color:#cdc3ad;margin:5px 0 6px;font-style:italic}",
  ".vle-jr-tags{display:flex;flex-wrap:wrap;gap:4px;align-items:center}",
  ".vle-jr-tag{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:5px;border:1px solid rgba(var(--vg-rgb),.2);opacity:.85}",
  ".vle-jr-tag.w-defining{border-color:rgba(var(--vg-rgb),.6);color:var(--vle-gold)}",
  ".vle-jr-tag.w-significant{border-color:rgba(var(--vg-rgb),.4)}",
  ".vle-jr-day{margin-left:auto;font:600 9px/1 var(--vmono);opacity:.5}",
  // ---- relation change history ----
  ".vle-hist{margin-top:7px;border-top:1px solid rgba(var(--vg-rgb),.14);padding-top:5px}",
  ".vle-hist>summary{cursor:pointer;list-style:none;font:600 9px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;opacity:.5}",
  ".vle-hist>summary::-webkit-details-marker{display:none}.vle-hist>summary::before{content:'\u25B8 '}",
  ".vle-hist[open]>summary::before{content:'\u25BE '}",
  ".vle-hist-sec{font:600 9px/1 var(--vmono);text-transform:uppercase;opacity:.45;margin:6px 0 3px}",
  ".vle-hist-row{display:flex;gap:7px;align-items:baseline;font-size:11px;padding:1px 0}",
  ".vle-hist-t{flex:none;width:30px;font:600 9px/1 var(--vmono);opacity:.5}",
  ".vle-hist-ev{font:600 9px/1 var(--vmono);padding:1px 5px;border-radius:5px}",
  ".vle-hist-ev.add{color:var(--v-pos-i);border:1px solid color-mix(in srgb,var(--v-pos) 40%,transparent)}",
  ".vle-hist-ev.rm{color:var(--v-neg-i);border:1px solid color-mix(in srgb,var(--v-neg) 40%,transparent);text-decoration:line-through}",
  ".vle-hist-sc{font:600 9px/1.3 var(--vmono);color:var(--vi2)}",
  ".vle-hist-why{opacity:.55;font-style:italic;font-size:10px}",
  // ---- injection tab ----
  ".vle-inj-hint{font-size:10px;opacity:.55;margin-right:auto}",
  ".vle-inj-list{display:flex;flex-direction:column;gap:6px}",
  ".vle-inj{border:1px solid rgba(var(--vg-rgb),.18);border-radius:9px;overflow:hidden;background:rgba(20,18,14,.4)}",
  ".vle-inj-top{display:flex;align-items:center;gap:8px;padding:7px 10px;cursor:pointer}",
  ".vle-inj-top:hover{background:rgba(var(--vg-rgb),.06)}",
  ".vle-inj-turn{font:600 9px/1 var(--vmono);color:var(--vle-gold);flex:none}",
  ".vle-inj-reasons{flex:1;display:flex;flex-wrap:wrap;gap:4px}",
  ".vle-inj-reason{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:var(--vr1);background:rgba(var(--vg-rgb),.1);color:var(--vi2)}",
  ".vle-inj-chars{font:600 9px/1 var(--vmono);opacity:.45;flex:none}",
  ".vle-inj-body{display:none;margin:0;padding:9px 11px;border-top:1px solid rgba(var(--vg-rgb),.16);font:500 10.5px/1.5 var(--vmono);color:#bcb29c;white-space:pre-wrap;word-break:break-word;max-height:320px;overflow-y:auto;background:rgba(12,10,8,.5)}",
  ".vle-inj-body.open{display:block}",
  // ---- journal book / shelf ----
  ".vle-shelf{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 9px}",
  ".vle-book{font:600 11px/1 var(--vserif);letter-spacing:.5px;color:var(--vi);background:linear-gradient(180deg,rgba(34,28,19,.9),rgba(20,17,12,.9));border:1px solid rgba(var(--vg-rgb),.3);border-radius:6px;padding:6px 10px;cursor:pointer;display:inline-flex;align-items:center;gap:6px}",
  ".vle-book:hover{border-color:var(--vle-gold);background:rgba(var(--vg-rgb),.16)}",
  ".vle-book-n{font:600 9px/1 var(--vmono);background:rgba(var(--vg-rgb),.2);color:var(--vle-gold);border-radius:7px;padding:2px 6px}",
  ".vle-book-head{display:flex;align-items:center;gap:8px;margin-bottom:9px;padding-bottom:7px;border-bottom:1px solid rgba(var(--vg-rgb),.22)}",
  ".vle-book-title{font-family:var(--vserif);font-size:17px;letter-spacing:1px;color:var(--vi);flex:1}",
  // ---- floating dashboard ----
  ".vld{display:flex;flex-direction:column;gap:calc(16px * var(--vscale))}",
  ".vld-sec{display:flex;flex-direction:column;gap:calc(8px * var(--vscale));padding:calc(12px * var(--vscale)) calc(13px * var(--vscale));border:1px solid rgba(var(--vg-rgb),.14);border-radius:var(--vr3);background:linear-gradient(168deg,var(--vsurf-1),var(--vsurf-2))}",
  ".vld-h{font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:1.5px;text-transform:uppercase;color:var(--vg);opacity:.85;display:flex;align-items:center;gap:7px}",
  ".vld-statbar{display:flex;flex-wrap:wrap;gap:7px}",
  ".vld-stat{font:600 calc(11px * var(--vscale))/1 var(--vmono);color:var(--vi2);background:rgba(var(--vg-rgb),.1);border:1px solid rgba(var(--vg-rgb),.24);border-radius:8px;padding:7px 11px;display:inline-flex;gap:6px}",
  ".vld-stat b{color:var(--vle-gold);font-weight:600;opacity:.85}",
  ".vld-loc{font-family:var(--vserif);font-size:calc(18px * var(--vscale));color:var(--vi);font-style:italic;line-height:1.3}",
  ".vld-tension-row{display:flex;align-items:center;gap:12px}",
  ".vld-tension{position:relative;flex:1;height:8px;border-radius:5px;background:rgba(255,255,255,.07);overflow:hidden}",
  ".vld-tension-f{position:absolute;left:0;top:0;height:8px;border-radius:5px;transition:width .3s;box-shadow:0 0 8px currentColor}",
  ".vld-tension-n{flex:none;min-width:38px;text-align:right;font:600 calc(11px * var(--vscale))/1 var(--vmono);opacity:.7}",
  ".vld-pc{border:1px solid rgba(var(--vg-rgb),.16);border-left:3px solid rgba(var(--vg-rgb),.5);border-radius:0 var(--vr3) var(--vr3) 0;background:rgba(var(--vg-rgb),.05);padding:calc(9px * var(--vscale)) calc(12px * var(--vscale))}",
  ".vld-pc+.vld-pc{margin-top:7px}",
  ".vld-pc-top{display:flex;align-items:center;gap:8px;flex-wrap:wrap}",
  ".vld-pc-n{font-family:var(--vserif);font-size:calc(17px * var(--vscale));color:var(--vi);font-weight:600}",
  ".vld-mood{font:600 calc(9px * var(--vscale))/1 var(--vmono);text-transform:uppercase;letter-spacing:.5px;padding:3px 7px;border-radius:var(--vr1);background:color-mix(in srgb,var(--v-pos) 20%,transparent);color:var(--v-pos-i)}",
  ".vld-cond{font:600 calc(9px * var(--vscale))/1 var(--vmono);text-transform:uppercase;letter-spacing:.5px;padding:3px 7px;border-radius:var(--vr1);background:color-mix(in srgb,var(--v-neg) 18%,transparent);color:var(--v-neg-i)}",
  ".vld-doing{font-size:calc(13px * var(--vscale));opacity:.8;margin-top:5px;line-height:1.45}",
  ".vld-thought{font-family:var(--vserif);font-style:italic;font-size:calc(15px * var(--vscale));color:var(--vi2);margin-top:6px;line-height:1.5;padding-left:10px;border-left:2px solid rgba(var(--vg-rgb),.3)}",
  ".vld-rel{display:flex;align-items:center;gap:7px;flex-wrap:wrap;font-size:calc(13px * var(--vscale));padding:5px 0;border-top:1px solid rgba(var(--vg-rgb),.08)}",
  ".vld-rel:first-child{border-top:none}",
  ".vld-rel-p{color:var(--vi)}.vld-rel-s{margin-left:auto;font:600 calc(9px * var(--vscale))/1 var(--vmono);opacity:.6}",
  ".vld-cat{font:600 calc(9px * var(--vscale))/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;padding:2px 6px;border-radius:5px;color:var(--c);border:1px solid color-mix(in srgb,var(--c) 45%,transparent)}",
  ".vld-thread{display:flex;justify-content:space-between;gap:8px;font-size:calc(13px * var(--vscale));padding:4px 0 4px 9px;border-left:2px solid rgba(var(--vg-rgb),.3)}",
  ".vld-thread+.vld-thread{border-top:1px solid rgba(var(--vg-rgb),.08)}",
  ".vld-thread-s{font:600 calc(9px * var(--vscale))/1 var(--vmono);color:var(--vle-gold);opacity:.75}",
  ".vld-par{border:1px solid color-mix(in srgb,var(--v-info) 22%,transparent);border-radius:10px;background:color-mix(in srgb,var(--v-info) 7%,transparent);padding:calc(8px * var(--vscale)) calc(11px * var(--vscale))}",
  ".vld-par+.vld-par{margin-top:6px}",
  ".vld-par-who{font-family:var(--vserif);font-size:calc(15px * var(--vscale));color:var(--v-info)}",
  ".vld-par-w{font:600 calc(9px * var(--vscale))/1 var(--vmono);opacity:.55}",
  ".vld-par-act{font-size:calc(12.5px * var(--vscale));opacity:.82;margin-top:3px;line-height:1.45}",
  ".vld-rec{font-size:calc(12.5px * var(--vscale));line-height:1.55;padding:5px 0;color:var(--vi2);border-top:1px solid rgba(var(--vg-rgb),.08)}",
  ".vld-rec:first-child{border-top:none}",
  ".vld-rec-k{font:600 calc(9px * var(--vscale))/1 var(--vmono);text-transform:uppercase;letter-spacing:.5px;color:var(--vle-gold);background:rgba(var(--vg-rgb),.14);border-radius:5px;padding:3px 6px;margin-right:7px}",
  // ---- Vault tab ----
  ".vlv-catbar{display:flex;flex-wrap:wrap;gap:5px;margin:0 0 10px}",
  ".vlv-chip{display:inline-flex;align-items:center;gap:5px;font:600 10px/1 var(--vmono);letter-spacing:.4px;color:var(--vi2);background:rgba(var(--vg-rgb),.07);border:1px solid var(--vle-gold-soft);border-radius:8px;padding:5px 9px;cursor:pointer;opacity:.78}",
  ".vlv-chip:hover{opacity:1}.vlv-chip.on{opacity:1;border-color:var(--c,rgba(var(--vg-rgb),.5));background:color-mix(in srgb,var(--c,var(--vg)) 18%,transparent);color:var(--vi)}",
  ".vlv-chip.add{color:var(--vle-gold);border-style:dashed}",
  ".vlv-glyph{color:var(--c,var(--vle-gold))}",
  ".vlv-cn{font-size:9px;background:rgba(var(--vg-rgb),.18);color:var(--vle-gold);border-radius:7px;padding:1px 5px}",
  ".vlv-gear{opacity:.5;margin-left:2px}.vlv-gear:hover{opacity:1;color:var(--vle-gold)}",
  ".vlv-grid{display:flex;flex-direction:column;gap:7px}",
  ".vlv-entry{border:1px solid rgba(var(--vg-rgb),.16);border-left:3px solid var(--c,#8c8478);border-radius:0 var(--vr2) var(--vr2) 0;background:rgba(22,20,16,.42);padding:8px 11px}",
  ".vlv-entry.off{opacity:.5}",
  ".vlv-entry-top{display:flex;align-items:center;gap:7px}",
  ".vlv-entry-cat{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.5px;color:var(--c,var(--vi2))}",
  ".vlv-firing{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;color:var(--v-pos-i);background:color-mix(in srgb,var(--v-pos) 18%,transparent);border-radius:var(--vr1);padding:2px 6px}",
  ".vlv-entry-ctl{margin-left:auto;display:inline-flex;gap:3px}",
  ".vlv-keys{font:600 10px/1.3 var(--vmono);color:var(--vle-gold);margin-top:5px;opacity:.85}",
  ".vlv-content{font-size:12px;line-height:1.5;color:#cdc3ad;margin-top:4px;white-space:pre-wrap;word-break:break-word}",
  ".vlv-badge{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;color:var(--v-info);margin-top:6px;opacity:.7;display:flex;align-items:center;gap:6px}",
  ".vlv-unlink{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid rgba(var(--vg-rgb),.2);border-radius:5px;padding:2px 6px;cursor:pointer}",
  ".vlv-unlink:hover{color:var(--vle-gold);background:rgba(var(--vg-rgb),.2)}",
  ".vlv-title{font-family:var(--vserif);font-size:15px;color:var(--vi);margin-top:4px}",
  ".vlv-suggest{display:flex;flex-wrap:wrap;align-items:center;gap:6px;margin:0 0 10px;padding:7px 9px;border:1px dashed rgba(var(--vg-rgb),.3);border-radius:9px;background:rgba(var(--vg-rgb),.05)}",
  ".vlv-suggest-h{font:600 9px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vle-gold);opacity:.8}",
  ".vlv-sug{display:inline-flex;align-items:center;gap:5px;font-size:11px;background:rgba(22,20,16,.5);border:1px solid var(--vle-gold-soft);border-radius:20px;padding:3px 5px 3px 9px}",
  ".vlv-sug-l{color:var(--vi)}.vlv-sug-r{font:600 9px/1 var(--vmono);opacity:.5}",
  ".vlv-sug-y,.vlv-sug-n{width:18px;height:18px;display:grid;place-items:center;border-radius:50%;border:none;cursor:pointer;font-size:11px}",
  ".vlv-sug-y{background:color-mix(in srgb,var(--v-pos) 25%,transparent);color:var(--v-pos-i)}.vlv-sug-y:hover{background:color-mix(in srgb,var(--v-pos) 45%,transparent)}",
  ".vlv-sug-n{background:rgba(255,255,255,.06);color:var(--vi2)}.vlv-sug-n:hover{background:color-mix(in srgb,var(--v-neg) 25%,transparent);color:var(--v-neg-i)}",
  ".vlv-bklist{display:flex;flex-direction:column;gap:5px;margin-bottom:4px}",
  ".vlv-bk{display:flex;align-items:center;gap:7px;padding:6px 9px;border:1px solid var(--vle-gold-soft);border-radius:8px;background:rgba(22,20,16,.4)}",
  ".vlv-bk-n{flex:1;font-family:var(--vserif);font-size:14px;color:var(--vi)}",
  ".vlv-bk-tag{font:600 9px/1 var(--vmono);text-transform:uppercase;color:var(--v-info);opacity:.7}",
  ".vlv-bk-ctl{display:inline-flex;align-items:center;gap:5px}",
  ".vlv-bk-att{font:600 9px/1 var(--vmono);letter-spacing:.4px;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid rgba(var(--vg-rgb),.22);border-radius:6px;padding:4px 8px;cursor:pointer}",
  ".vlv-bk-att.on{color:var(--v-pos-i);border-color:color-mix(in srgb,var(--v-pos) 40%,transparent);background:color-mix(in srgb,var(--v-pos) 16%,transparent)}",
  ".vlv-current{display:flex;align-items:center;gap:8px;margin:0 0 9px;padding:6px 10px;border:1px solid var(--vle-gold-soft);border-radius:8px;background:rgba(var(--vg-rgb),.05)}",
  ".vlv-current-l{font:600 9px/1 var(--vmono);letter-spacing:.6px;text-transform:uppercase;opacity:.5}",
  ".vlv-current-n{font-family:var(--vserif);font-size:14px;color:var(--vle-gold);cursor:pointer}",
  ".vlv-current-n:hover{text-decoration:underline}",
  ".vlv-scopebar{display:flex;gap:5px;margin:0 0 8px}",
  ".vlv-scope{flex:1;font:600 9.5px/1 var(--vmono);letter-spacing:.4px;color:var(--vi2);background:rgba(var(--vg-rgb),.06);border:1px solid var(--vle-gold-soft);border-radius:8px;padding:7px 10px;cursor:pointer;opacity:.7;display:inline-flex;align-items:center;justify-content:center;gap:6px}",
  ".vlv-scope:hover{opacity:.95}.vlv-scope.on{opacity:1;color:var(--vle-gold);border-color:rgba(var(--vg-rgb),.5);background:rgba(var(--vg-rgb),.16)}",
  ".vlv-pending{margin:0 0 10px;padding:8px 10px;border:1px solid rgba(180,142,208,.34);border-radius:9px;background:rgba(180,142,208,.07)}",
  ".vlv-pending-h{font:600 9px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--v-warn);display:flex;align-items:center;gap:6px;margin-bottom:6px}",
  ".vlv-pend{border-top:1px solid rgba(180,142,208,.18);padding:6px 0}",
  ".vlv-pend:first-of-type{border-top:none}",
  ".vlv-pend-top{display:flex;align-items:center;gap:7px}",
  ".vlv-pend-n{flex:1;font-family:var(--vserif);font-size:14px;color:var(--vi)}",
  ".vlv-pend-ctl{display:inline-flex;gap:4px}",
  ".vlv-pend-y,.vlv-pend-e,.vlv-pend-n2{width:20px;height:20px;display:grid;place-items:center;border-radius:5px;border:none;cursor:pointer;font-size:11px}",
  ".vlv-pend-y{background:color-mix(in srgb,var(--v-pos) 25%,transparent);color:var(--v-pos-i)}.vlv-pend-y:hover{background:color-mix(in srgb,var(--v-pos) 45%,transparent)}",
  ".vlv-pend-e{background:rgba(var(--vg-rgb),.14);color:var(--vle-gold)}.vlv-pend-e:hover{background:rgba(var(--vg-rgb),.28)}",
  ".vlv-pend-n2{background:rgba(255,255,255,.06);color:var(--vi2)}.vlv-pend-n2:hover{background:color-mix(in srgb,var(--v-neg) 25%,transparent);color:var(--v-neg-i)}",
  ".vlv-pend-c{font-size:11.5px;line-height:1.45;opacity:.75;margin-top:3px}",
  // ---- Customize panel (theme) ----
  ".vle-cz{display:flex;flex-direction:column;gap:7px}",
  ".vle-cz-h{font:600 calc(9.5px * var(--vscale))/1 var(--vmono);letter-spacing:1px;text-transform:uppercase;color:var(--vg);opacity:.7;margin-top:6px}",
  ".vle-cz-row{display:flex;align-items:center;gap:9px}",
  ".vle-cz-color{width:42px;height:34px;padding:0;border:1px solid rgba(var(--vg-rgb),.4);border-radius:9px;background:transparent;cursor:pointer}",
  ".vle-cz-hex{flex:1;font:600 13px/1 var(--vmono);letter-spacing:1px;text-transform:uppercase;color:var(--vi);background:rgba(12,10,8,.6);border:1px solid rgba(var(--vg-rgb),.26);border-radius:8px;padding:9px 11px;outline:none}",
  ".vle-cz-hex:focus{border-color:var(--vg)}",
  ".vle-cz-sel{flex:1;font-family:var(--vserif);font-size:15px;color:var(--vi);background:rgba(12,10,8,.6);border:1px solid rgba(var(--vg-rgb),.26);border-radius:8px;padding:9px 11px;cursor:pointer}",
  ".vle-cz-range{flex:1;accent-color:var(--vg);cursor:pointer}",
  ".vle-cz-sv{flex:none;min-width:48px;text-align:right;font:600 12px/1 var(--vmono);color:var(--vg)}",
  ".vle-skins{display:grid;grid-template-columns:repeat(auto-fill,minmax(96px,1fr));gap:7px}",
  ".vle-skin{display:flex;flex-direction:column;align-items:center;gap:6px;padding:9px 6px;border:1px solid rgba(var(--vg-rgb),.2);border-radius:11px;background:rgba(var(--vg-rgb),.05);cursor:pointer;transition:border-color .15s,background .15s}",
  ".vle-skin:hover{background:rgba(var(--vg-rgb),.12)}",
  ".vle-skin.on{border-color:var(--sw);background:color-mix(in srgb,var(--sw) 16%,transparent);box-shadow:0 0 10px color-mix(in srgb,var(--sw) 35%,transparent)}",
  ".vle-skin-sw{width:100%;height:14px;border-radius:5px;background:linear-gradient(90deg,var(--sw),color-mix(in srgb,var(--sw) 35%,transparent));box-shadow:0 0 6px color-mix(in srgb,var(--sw) 50%,transparent)}",
  ".vle-skin-n{font:600 9.5px/1.2 var(--vmono);letter-spacing:.3px;text-align:center;color:var(--vi2)}",
  // ---- layout picker + dashboard layout modes ----
  ".vle-lays{display:grid;grid-template-columns:repeat(auto-fill,minmax(84px,1fr));gap:7px}",
  ".vle-lay{display:flex;flex-direction:column;align-items:center;gap:6px;padding:10px 6px;border:1px solid rgba(var(--vg-rgb),.2);border-radius:11px;background:rgba(var(--vg-rgb),.05);cursor:pointer;color:var(--vi2);transition:border-color .15s,background .15s}",
  ".vle-lay:hover{background:rgba(var(--vg-rgb),.12)}",
  ".vle-lay.on{border-color:var(--vg);background:rgba(var(--vg-rgb),.16);box-shadow:0 0 10px rgba(var(--vg-rgb),.3)}",
  ".vle-lay-g{font-size:20px;color:var(--vg);line-height:1}",
  ".vle-lay-n{font:600 9px/1.2 var(--vmono);letter-spacing:.3px;text-align:center}",
  // dashboard density (scales the section gap + inner padding)
  ".vld-inner{display:flex;flex-direction:column;gap:calc(16px * var(--vscale) * var(--vdensity,1))}",
  ".vld-inner[data-density='compact']{gap:calc(9px * var(--vscale))}",
  ".vld-inner[data-density='compact'] .vld-sec{padding:calc(8px * var(--vscale)) calc(10px * var(--vscale));gap:calc(5px * var(--vscale));border-radius:10px}",
  ".vld-inner[data-density='roomy']{gap:calc(22px * var(--vscale))}",
  ".vld-inner[data-density='roomy'] .vld-sec{padding:calc(16px * var(--vscale)) calc(17px * var(--vscale));gap:calc(11px * var(--vscale))}",
  ".vld-inner[data-density='roomy'] .vld-thought,.vld-inner[data-density='roomy'] .vld-rec{font-size:calc(15px * var(--vscale));line-height:1.65}",
  // 2-column (Director) — masonry-ish via CSS columns; collapses under 380px
  ".vld-inner[data-cols='2']{display:block;column-count:2;column-gap:calc(14px * var(--vscale))}",
  ".vld-inner[data-cols='2'] .vld-sec,.vld-inner[data-cols='2'] .vld-fold{break-inside:avoid;margin-bottom:calc(14px * var(--vscale));display:inline-block;width:100%}",
  "@container (max-width:380px){.vld-inner[data-cols='2']{column-count:1}}",
  ".vld-stage,.vlf-body{container-type:inline-size}",
  // collapsed sections (accordion)
  ".vld-fold{border:1px solid rgba(var(--vg-rgb),.14);border-radius:var(--vr3);background:linear-gradient(168deg,var(--vsurf-1),var(--vsurf-2));overflow:hidden}",
  ".vld-fold>summary{cursor:pointer;list-style:none;padding:calc(9px * var(--vscale)) calc(13px * var(--vscale));font:600 calc(10px * var(--vscale))/1 var(--vmono);letter-spacing:1.5px;text-transform:uppercase;color:var(--vg);opacity:.85}",
  ".vld-fold>summary::-webkit-details-marker{display:none}.vld-fold>summary::before{content:'\u25B8 '}",
  ".vld-fold[open]>summary::before{content:'\u25BE '}",
  ".vld-fold[open]>summary{border-bottom:1px solid rgba(var(--vg-rgb),.12)}",
  ".vld-fold-b{padding:calc(10px * var(--vscale)) calc(13px * var(--vscale))}",
  ".vld-fold-b .vld-sec{border:none;background:none;padding:0}",
  // ---- Customize panel: tabs, sliders, reset, custom-layout editor ----
  ".vle-czt-bar{display:flex;gap:3px;flex-wrap:wrap;margin-bottom:10px;border-bottom:1px solid rgba(var(--vg-rgb),.18);padding-bottom:8px}",
  ".vle-czt{font:600 9.5px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vi2);background:transparent;border:1px solid transparent;border-radius:7px;padding:6px 10px;cursor:pointer;opacity:.7}",
  ".vle-czt:hover{opacity:1}.vle-czt.on{opacity:1;color:var(--vg);background:rgba(var(--vg-rgb),.14);border-color:rgba(var(--vg-rgb),.35)}",
  ".vle-cz-rst{margin-left:auto;cursor:pointer;opacity:.5;font-size:13px}.vle-cz-rst:hover{opacity:1;color:var(--vg)}",
  ".vle-cz-h{display:flex;align-items:center}",
  ".vle-cz-btn{font:600 9.5px/1 var(--vmono);letter-spacing:.4px;text-transform:uppercase;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid rgba(var(--vg-rgb),.24);border-radius:8px;padding:7px 11px;cursor:pointer}",
  ".vle-cz-btn:hover{background:rgba(var(--vg-rgb),.2);color:var(--vg)}",
  ".vle-cz-btn.danger:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vle-cz-chk{display:inline-flex;align-items:center;gap:6px;font:500 12px/1 var(--vmono);color:var(--vi2);cursor:pointer}",
  ".vle-cz-chk input{accent-color:var(--vg);cursor:pointer}",
  ".vle-cz-mini{font:600 9px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;opacity:.6}",
  ".vle-cz-note{font-size:11px;line-height:1.5;opacity:.6;padding:4px 0}",
  // custom layout editor
  ".vle-clays{display:flex;flex-direction:column;gap:4px;margin-bottom:8px}",
  ".vle-clr{display:flex;align-items:center;gap:6px;padding:6px 8px;border:1px solid rgba(var(--vg-rgb),.16);border-radius:8px;background:rgba(var(--vg-rgb),.05)}",
  ".vle-clr.off{opacity:.5}",
  ".vle-clr-up,.vle-clr-dn{cursor:pointer;color:var(--vg);opacity:.7;font-size:12px;width:16px;text-align:center}",
  ".vle-clr-up:hover,.vle-clr-dn:hover{opacity:1}.vle-clr-up[data-dis],.vle-clr-dn[data-dis]{opacity:.2;pointer-events:none}",
  ".vle-clr-n{flex:1;font-family:var(--vserif);font-size:14px;color:var(--vi)}",
  ".vle-clr-b{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px;color:var(--vi2);background:rgba(var(--vg-rgb),.08);border:1px solid rgba(var(--vg-rgb),.2);border-radius:6px;padding:4px 7px;cursor:pointer}",
  ".vle-clr-b.on{color:var(--vg);border-color:rgba(var(--vg-rgb),.45);background:rgba(var(--vg-rgb),.18)}",
  // controller-traversal trace (flat + tree drill)
  ".vle-inj-trace{margin:4px 0 2px;padding:6px 8px;border-left:2px solid rgba(var(--vg-rgb),.35);background:rgba(var(--vg-rgb),.05);border-radius:0 6px 6px 0;font:500 10px/1.5 var(--vmono)}",
  ".vle-inj-scene{color:var(--vle-dim);font-style:italic;margin-bottom:4px}",
  ".vle-inj-cands{color:var(--vle-dim);margin-top:3px}",
  ".vle-inj-cand{display:inline-block;margin:2px 4px 0 0;padding:1px 5px;border-radius:3px;border:1px solid rgba(255,255,255,.12);color:var(--vle-dim);font-size:9px}",
  ".vle-inj-cand.on{color:var(--vle-gold);border-color:rgba(var(--vg-rgb),.5);background:rgba(var(--vg-rgb),.12)}",
  ".vle-inj-cand.exp{color:#8fb0c9;border-color:rgba(143,176,201,.4)}",
  ".vle-inj-step{display:flex;flex-wrap:wrap;align-items:center;gap:4px;padding:3px 0;border-top:1px dashed rgba(255,255,255,.08)}",
  ".vle-inj-stepn{color:var(--vle-gold);font-weight:600;margin-right:4px}",
  ".vle-inj-stepf{color:var(--vle-dim);margin-right:6px;font-size:9px}",
  ".vle-inj-tree{border-left-color:rgba(var(--vg-rgb),.5)}",
  // keyboard focus ring (a11y): one rule for the whole shell + graph nodes
  ".vle-root :focus-visible,.vlf :focus-visible,.vlfm :focus-visible{outline:2px solid var(--vg);outline-offset:2px;border-radius:var(--vr1)}",
  ".vlf-launch:focus-visible{outline:2px solid var(--vg);outline-offset:2px}",
  ".vlg-node:focus-visible{outline:none}.vlg-node:focus-visible .vlg-node-c{stroke:var(--vg);stroke-width:3.4}.vlg-node:focus-visible .vlg-node-l{opacity:1}",
  // factions
  ".vle-sec-title{font:600 11px/1 var(--vmono);letter-spacing:.5px;text-transform:uppercase;color:var(--vle-gold);opacity:.85;margin-right:auto}",
  ".vle-sec-gap{margin-top:14px}",
  ".vle-fac-av{background:rgba(var(--vg-rgb),.16);color:var(--vle-gold)}",
  ".vle-fac-stand{font:600 9px/1 var(--vmono);text-transform:uppercase;letter-spacing:.4px}",
  ".vle-fac-stand.warm{color:var(--v-pos-i)}", ".vle-fac-stand.cool{color:var(--v-neg-i)}", ".vle-fac-stand.neu{color:var(--vle-dim)}",
  ".vle-fac-meter{display:block;margin-top:4px;max-width:220px}",
  ".vle-fac-mems{display:flex;flex-wrap:wrap;gap:4px;margin-top:4px}",
  ".vle-fac-mem{display:inline-flex;align-items:center;gap:3px;font:500 9px/1.4 var(--vmono);padding:2px 4px;border-radius:var(--vr1);border:1px solid rgba(255,255,255,.12);color:var(--vle-dim)}",
  ".vle-fac-x{background:none;border:0;color:var(--vle-dim);cursor:pointer;font-size:11px;line-height:1;padding:0 0 0 2px;opacity:.6}",
  ".vle-fac-x:hover{opacity:1;color:var(--v-neg-i)}",
  ".vle-fac-more{font:500 9px/1.4 var(--vmono);color:var(--vle-dim);opacity:.7}",
  ".vle-dim{opacity:.6}",
  // status-on-avatar: cards self-describe presence (signal lands where the eye does)
  ".vle-card--present .vle-av{box-shadow:0 0 0 2px var(--vg),0 0 9px rgba(var(--vg-rgb),.5)}",
  ".vle-card--active .vle-av{box-shadow:0 0 0 2px rgba(var(--vg-rgb),.45)}",
  ".vle-card--mentioned .vle-av{box-shadow:inset 0 0 0 1px rgba(var(--vg-rgb),.3);opacity:.8}",
  ".vle-card--added .vle-av{opacity:.55}",
  ".vle-card--mentioned,.vle-card--added{opacity:.92}",
].join('\n');
