/**
 * Themed CSS for the VELLUM shell + components. Illuminated-manuscript palette
 * via CSS variables so skins/host theme can override. Single string loaded via
 * spindle.dom.addStyle.
 */
export const STYLES = [
  ":root{--vle-gold:#cda84e;--vle-gold-soft:rgba(205,168,78,.16);--vle-ink:#e7d6ad;--vle-bg:rgba(20,18,14,.55)}",
  ".vle-root{font-family:'Cormorant Garamond',Georgia,serif;color:var(--vle-ink);padding:10px 12px}",
  ".vle-head{display:flex;align-items:center;gap:7px;font-size:18px;letter-spacing:1px;padding-bottom:8px;border-bottom:1px solid var(--vle-gold-soft)}",
  ".vle-mark{color:var(--vle-gold)}",
  ".vle-ver{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:1px;text-transform:uppercase;opacity:.6;color:var(--vle-gold)}",
  ".vle-stats{margin-left:auto;font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;opacity:.55}",
  // tab bar
  ".vle-tabbar{display:flex;gap:4px;margin:9px 0;flex-wrap:wrap}",
  ".vle-tabbtn{font:600 10px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#cdbfa0;background:rgba(205,168,78,.07);border:1px solid var(--vle-gold-soft);border-radius:7px;padding:6px 11px;cursor:pointer;opacity:.7;transition:opacity .15s,background .15s}",
  ".vle-tabbtn:hover{opacity:.95}",
  ".vle-tabbtn.on{opacity:1;background:rgba(205,168,78,.2);border-color:rgba(205,168,78,.45);color:var(--vle-gold)}",
  ".vle-toolbar{display:flex;flex-wrap:wrap;gap:4px;margin:0 0 10px}",
  ".vle-qol{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#bcae8e;background:rgba(205,168,78,.06);border:1px solid rgba(205,168,78,.18);border-radius:7px;padding:5px 9px;cursor:pointer;transition:background .15s,color .15s}",
  ".vle-qol:hover{background:rgba(205,168,78,.2);color:var(--vle-gold);border-color:rgba(205,168,78,.4)}",
  ".vle-qol[data-qol='clear']:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vle-body{min-height:60px}",
  ".vle-empty{padding:24px 8px;text-align:center;opacity:.65;font-size:14px;line-height:1.6}",
  ".vle-empty.sm{padding:10px;font-size:12px}",
  // section headers + counts
  ".vle-sec-h{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:1px;text-transform:uppercase;opacity:.5;margin:12px 0 6px;display:flex;align-items:center;gap:6px}",
  ".vle-n{font-size:8px;background:var(--vle-gold-soft);color:var(--vle-gold);border-radius:8px;padding:2px 6px}",
  ".vle-scene{font-size:14px;font-style:italic;opacity:.85;padding:4px 2px}",
  ".vle-tension{font:600 9px/1 'JetBrains Mono',monospace;color:#c96a6a;letter-spacing:.5px;margin-left:6px}",
  // cast cards
  ".vle-cards{display:flex;flex-direction:column;gap:5px}",
  ".vle-card{display:flex;align-items:center;gap:9px;padding:7px 9px;border:1px solid var(--vle-gold-soft);border-radius:9px;background:linear-gradient(170deg,rgba(28,25,20,.45),rgba(18,16,12,.35))}",
  ".vle-card.on{border-color:var(--vle-gold);box-shadow:0 0 8px rgba(205,168,78,.18)}",
  ".vle-av{flex:none;width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:rgba(205,168,78,.18);color:var(--vle-gold);font-weight:600;font-size:12px}",
  ".vle-card-main{display:flex;flex-direction:column;gap:1px;min-width:0}",
  ".vle-card-n{font-size:14px}",
  ".vle-star{color:var(--vle-gold);font-size:9px}",
  ".vle-card-meta{font:600 9px/1.2 'JetBrains Mono',monospace;opacity:.6}",
  ".vle-card-app{font-size:11px;opacity:.7;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  // tracks + memory
  ".vle-track{display:flex;justify-content:space-between;gap:8px;font-size:12px;padding:3px 8px;border-left:2px solid var(--vle-gold-soft);margin-bottom:3px}",
  ".vle-track-s{font:600 9px/1.3 'JetBrains Mono',monospace;color:var(--vle-gold);opacity:.8}",
  ".vle-mem{display:flex;gap:7px;font-size:12px;padding:4px 0;line-height:1.45;align-items:baseline}",
  ".vle-mem-tier{flex:none;font:600 7px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.5px;padding:2px 5px;border-radius:5px;opacity:.85}",
  ".vle-mem-tier.t-turn{color:#8c8478;border:1px solid rgba(140,132,120,.4)}",
  ".vle-mem-tier.t-chapter{color:#7ea6b0;border:1px solid rgba(126,166,176,.4)}",
  ".vle-mem-tier.t-arc{color:var(--vle-gold);border:1px solid rgba(205,168,78,.4)}",
  // relations
  ".vle-rel-grid{display:flex;flex-direction:column;gap:7px}",
  ".vle-rel-card{border:1px solid var(--vle-gold-soft);border-radius:9px;padding:8px 10px;background:rgba(22,20,16,.4)}",
  ".vle-rel-top{display:flex;justify-content:space-between;align-items:center;gap:8px}",
  ".vle-rel-pair{font-size:14px}",
  ".vle-rel-sent{font:600 9px/1 'JetBrains Mono',monospace;opacity:.7}",
  ".vle-rel-label{font-size:12px;font-style:italic;opacity:.75;margin:3px 0}",
  ".vle-cats{display:flex;flex-wrap:wrap;gap:4px;margin:5px 0}",
  ".vle-cat{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.5px;padding:2px 6px;border-radius:6px;color:var(--c);border:1px solid color-mix(in srgb,var(--c) 45%,transparent)}",
  ".vle-st{font:600 8px/1 'JetBrains Mono',monospace;text-transform:uppercase;padding:2px 6px;border-radius:6px;opacity:.6;border:1px solid var(--vle-gold-soft)}",
  ".vle-bars{display:flex;flex-direction:column;gap:3px;margin-top:4px}",
  ".vle-bar{display:flex;align-items:center;gap:6px}",
  ".vle-bar-l{flex:none;width:30px;font:600 8px/1 'JetBrains Mono',monospace;opacity:.6}",
  ".vle-bar-t{position:relative;flex:1;height:5px;border-radius:3px;background:rgba(255,255,255,.06)}",
  ".vle-bar-mid{position:absolute;left:50%;top:-1px;width:1px;height:7px;background:rgba(255,255,255,.2)}",
  ".vle-bar-f{position:absolute;top:0;height:5px;border-radius:3px}",
  ".vle-bar-f.pos{background:#8fa67e}.vle-bar-f.neg{background:#c96a6a}",
  ".vle-bar-v{flex:none;width:30px;text-align:right;font:600 8px/1 'JetBrains Mono',monospace}",
  ".vle-bar-v.pos{color:#a9c089}.vle-bar-v.neg{color:#e09090}",
  // error boundary
  ".vlm-comp-error{padding:8px;font-size:11px;color:#e09090;border:1px solid rgba(201,106,106,.3);border-radius:8px;background:rgba(201,106,106,.08)}",
  ".vlm-comp-error span{opacity:.7;font-size:10px}",
  // ---- relationship graph ----
  ".vlg-wrap{display:flex;flex-direction:column;gap:8px}",
  ".vlg-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}",
  ".vlg-legend{display:flex;flex-wrap:wrap;gap:4px}",
  ".vlg-leg{display:inline-flex;align-items:center;gap:4px;font:600 8.5px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#cdbfa0;background:rgba(205,168,78,.08);border:1px solid var(--vle-gold-soft);border-radius:20px;padding:3px 9px;cursor:pointer;opacity:.6;transition:opacity .15s,background .15s}",
  ".vlg-leg:hover{opacity:.92}.vlg-leg.on{opacity:1;background:rgba(205,168,78,.2);border-color:rgba(205,168,78,.45)}",
  ".vlg-leg-dot{width:8px;height:8px;border-radius:50%;box-shadow:0 0 5px currentColor}",
  ".vlg-tools{display:flex;gap:4px}",
  ".vlg-tool{min-width:24px;height:24px;display:grid;place-items:center;font:600 13px/1 'JetBrains Mono',monospace;color:var(--vle-gold);background:rgba(205,168,78,.1);border:1px solid rgba(205,168,78,.24);border-radius:6px;cursor:pointer}",
  ".vlg-tool:hover{background:rgba(205,168,78,.22)}.vlg-tool.wide{padding:0 9px;font-size:9px;letter-spacing:.5px;text-transform:uppercase}",
  ".vlg-tool.wide.on{background:rgba(205,168,78,.26);border-color:rgba(205,168,78,.5)}",
  ".vlg-stage{position:relative;border:1px solid var(--vle-gold-soft);border-radius:14px;overflow:hidden;background:radial-gradient(130% 100% at 50% 0%,rgba(205,168,78,.06),transparent 55%),linear-gradient(168deg,rgba(26,22,16,.97),rgba(15,13,10,.99));box-shadow:inset 0 1px 40px rgba(0,0,0,.5),0 2px 18px rgba(0,0,0,.35)}",
  ".vlg-svg{display:block;width:100%;height:auto;min-height:360px;max-height:64vh;cursor:grab;touch-action:none}",
  ".vlg-svg:active{cursor:grabbing}",
  "[data-graph-pan]{transition:transform .09s ease-out}",
  // hulls
  ".vlg-hull-fill{opacity:.08;transition:opacity .3s;pointer-events:none}",
  ".vlg-wrap:hover .vlg-hull-fill{opacity:.12}",
  ".vlg-hull-label{font:600 13px/1 'Cormorant Garamond',Georgia,serif;letter-spacing:2px;text-transform:uppercase;opacity:.5;pointer-events:none}",
  "[data-factions='off'] .vlg-hulls{display:none}",
  // edges
  ".vlg-edge-line{opacity:.6;transition:opacity .2s,stroke-width .2s;filter:drop-shadow(0 0 2px rgba(0,0,0,.55))}",
  ".vlg-edge:hover .vlg-edge-line{opacity:1;stroke-width:5.5}",
  ".vlg-edge-hit{cursor:pointer}",
  // nodes
  ".vlg-node{cursor:grab}.vlg-node.vlg-dragging{cursor:grabbing}",
  ".vlg-node-glow{fill:rgba(205,168,78,0);opacity:0;transition:opacity .25s}",
  ".vlg-node-c{fill:url(#vlgNode);stroke:#8c8478;stroke-width:2;transition:stroke .2s,stroke-width .2s}",
  ".vlg-node-i{fill:#e7d6ad;font:600 12px/1 'Cormorant Garamond',Georgia,serif;letter-spacing:.5px;pointer-events:none;user-select:none}",
  ".vlg-node-l{fill:#cdbfa0;font:600 11px/1 'JetBrains Mono',monospace;opacity:0;transition:opacity .2s;pointer-events:none;paint-order:stroke;stroke:rgba(12,10,8,.92);stroke-width:3.5px}",
  ".vlg-node.is-present .vlg-node-c{fill:#3a2f16;stroke:var(--vle-gold);stroke-width:2.6;filter:url(#vlgGlow)}",
  ".vlg-node.is-present .vlg-node-glow{fill:rgba(205,168,78,.3);opacity:.95}",
  ".vlg-node.is-present .vlg-node-l{opacity:1;fill:#e7d6ad}",
  ".vlg-node.is-user .vlg-node-c{stroke:#e6c07a;stroke-width:3;stroke-dasharray:3 2}",
  ".vlg-node.is-mention .vlg-node-c{opacity:.5;stroke-dasharray:2 3}",
  ".vlg-node:hover .vlg-node-l{opacity:1}.vlg-node:hover .vlg-node-glow{opacity:.85;fill:rgba(205,168,78,.34)}",
  ".vlg-node:hover .vlg-node-c{stroke:var(--vle-gold);stroke-width:3}",
  // focus dimming
  ".vlg-focusing .vlg-edge.vlg-dim .vlg-edge-line{opacity:.08}",
  ".vlg-focusing .vlg-node.vlg-dim{opacity:.2}",
  ".vlg-focusing .vlg-node.vlg-hot .vlg-node-l{opacity:1}",
  ".vlg-node.vlg-hot .vlg-node-c{stroke:var(--vle-gold);stroke-width:3.2}",
  // tooltip
  ".vlg-tip{position:absolute;pointer-events:none;z-index:5;max-width:220px;background:rgba(18,15,11,.97);border:1px solid rgba(205,168,78,.34);border-radius:9px;padding:7px 11px;font:500 11px/1.5 'JetBrains Mono',monospace;color:#d8c9a8;box-shadow:0 8px 26px rgba(0,0,0,.55)}",
  ".vlg-tip b{color:#e7d6ad;font-family:'Cormorant Garamond',Georgia,serif;font-size:14px;letter-spacing:.5px}.vlg-tip span{opacity:.6}",
  ".vlg-hint{font-size:9px;line-height:1.5;opacity:.45;text-align:center;letter-spacing:.3px}",
  // ---- floating window ----
  ".vlf{position:fixed;z-index:9999;opacity:0;transform:translateY(8px) scale(.985);transition:opacity .22s ease,transform .22s cubic-bezier(.2,.8,.2,1);pointer-events:none;font-family:'Cormorant Garamond',Georgia,serif}",
  ".vlf.is-open{opacity:1;transform:none;pointer-events:auto}",
  ".vlf-frame{position:absolute;inset:0;display:flex;flex-direction:column;border-radius:16px;overflow:hidden;color:var(--vle-ink);background:linear-gradient(168deg,rgba(26,22,16,.97),rgba(15,13,10,.985));border:1px solid rgba(205,168,78,.45);box-shadow:0 24px 70px rgba(0,0,0,.6),0 2px 0 rgba(205,168,78,.12),inset 0 0 0 1px rgba(205,168,78,.10),inset 0 1px 50px rgba(205,168,78,.05);backdrop-filter:blur(7px)}",
  ".vlf-frame::before{content:'';position:absolute;inset:5px;border-radius:11px;border:1px solid rgba(205,168,78,.18);pointer-events:none}",
  ".vlf-frame::after{content:'';position:absolute;left:0;right:0;top:0;height:120px;background:radial-gradient(120% 90% at 50% -20%,rgba(205,168,78,.12),transparent 70%);pointer-events:none}",
  ".vlf-bar{position:relative;display:flex;align-items:center;gap:8px;padding:10px 12px 9px;cursor:grab;user-select:none;touch-action:none;border-bottom:1px solid rgba(205,168,78,.2);background:linear-gradient(180deg,rgba(205,168,78,.08),transparent)}",
  ".vlf-bar:active{cursor:grabbing}",
  ".vlf-mark{color:var(--vle-gold);font-size:14px;text-shadow:0 0 8px rgba(205,168,78,.5)}",
  ".vlf-title{font-size:17px;letter-spacing:2px;text-transform:uppercase;color:#e7d6ad}",
  ".vlf-actions{margin-left:auto;display:flex;gap:4px}",
  ".vlf-act{font:600 9px/1 'JetBrains Mono',monospace;letter-spacing:.5px;text-transform:uppercase;color:#cdbfa0;background:rgba(205,168,78,.1);border:1px solid rgba(205,168,78,.26);border-radius:7px;padding:4px 8px;cursor:pointer;transition:background .15s}",
  ".vlf-act:hover{background:rgba(205,168,78,.26);color:var(--vle-gold)}",
  ".vlf-x{width:24px;height:24px;display:grid;place-items:center;border-radius:7px;color:#cdbfa0;background:transparent;border:1px solid transparent;cursor:pointer;font-size:13px}",
  ".vlf-x:hover{color:#e09090;border-color:rgba(201,106,106,.4);background:rgba(201,106,106,.1)}",
  ".vlf-body{flex:1;overflow-y:auto;padding:12px 14px 16px;scrollbar-width:thin;scrollbar-color:rgba(205,168,78,.4) transparent}",
  ".vlf-body::-webkit-scrollbar{width:8px}.vlf-body::-webkit-scrollbar-thumb{background:rgba(205,168,78,.3);border-radius:4px}",
  ".vlf-grip{position:absolute;right:3px;bottom:3px;width:18px;height:18px;cursor:nwse-resize;touch-action:none;background:linear-gradient(135deg,transparent 45%,rgba(205,168,78,.5) 45%,rgba(205,168,78,.5) 55%,transparent 55%,transparent 70%,rgba(205,168,78,.5) 70%,rgba(205,168,78,.5) 80%,transparent 80%);border-bottom-right-radius:12px}",
].join('\n');
